import common
import database
import hashlib
import logging
import multiverse
import os
import survey
import threading
import typing
import uuid

# TODO: When updating snapshot I'll need to do something to make sure notes
# are preserved on systems/sectors. I could split notes in a separate table
# but it's probably easiest to just read the existing notes and set the
# notes on the new object before writing it to the db.
# TODO: When I switch to making a copy of the entire universe for custom
# universes, I need to add an option to regenerate the trade codes for
# the entire universe based on a specified rule set. It should default to
# the current selected rules but also have the option to use the trade
# codes as they appear on Traveller Map (explain the difference in a tooltip).
# The default universe will always use the Traveller Map trade codes.
# This will replace the ability to switch between modes dynamically which
# I removed as it complicated the code for generating remarks.
# Part of this work will probably need to be converting calculateMongooseTradeCodes
# to use string trade codes rather than traveller.TradeCode as the converter
# code doesn't have access to that logic.
# Alternatively it might be the time to convert DbObjects to use enums for things.
# It would make sense if it was the same ones as the traveller/astronomer code, so
# maybe I need some kind of low level basic type namespace.
# I've left the _RegenerateTradeCodesToolTip text as it could be a basis for the
# option when I add it to the custom universe creation dialog
# TODO: Top level functions should log that they were called

class UniverseInfo(object):
    def __init__(
            self,
            id: str,
            name: str,
            description: str
            ) -> None:
        common.validateStr(name='id', value=id, allowEmpty=False)
        common.validateStr(name='name', value=name, allowEmpty=False)
        common.validateStr(name='description', value=description, allowEmpty=True)

        self._id = id
        self._name = name
        self._description = description

    def id(self) -> str:
        return self._id

    def name(self) -> str:
        return self._name

    def description(self) -> str:
        return self._description

class UniverseManager(object):
    _RegistryFileName = 'registry.db'
    _UniversesDir = 'universes'

    _StockUniverseName = 'Traveller Map'
    _StockUniverseDescription = 'Sector data taken from Traveller Map'

    _lock = threading.RLock() # Recursive lock
    _instance = None # Singleton instance
    _initialised = False
    _multiversePath = None
    _registry = None

    def __init__(self) -> None:
        raise RuntimeError('Call instance() instead')

    @classmethod
    def instance(cls):
        if not cls._instance:
            with cls._lock:
                # Recheck instance as another thread could have created it between the
                # first check adn the lock
                if not cls._instance:
                    cls._instance = cls.__new__(cls)
        return cls._instance

    @staticmethod
    def initialise(
            multiversePath: str
            ) -> None:
        if UniverseManager._initialised:
            raise RuntimeError('The MultiverseDb singleton has already been initialised')

        UniverseManager._multiversePath = multiversePath

        universePath = UniverseManager._universeDirPath()
        os.makedirs(universePath, exist_ok=True)

        registryPath = UniverseManager._registryDbFilePath()
        UniverseManager._registry = multiverse.UniverseRegistry(registryPath=registryPath)

        UniverseManager._initialised = True

    def universeInfos(self) -> typing.List[multiverse.UniverseInfo]:
        return UniverseManager._registry.listUniverses()

    def universeInfoById(self, id: str) -> typing.Optional[multiverse.UniverseInfo]:
        return UniverseManager._registry.universeById(id=id)

    def universeDbById(self, id: str) -> typing.Optional[multiverse.UniverseDb]:
        universeInfo = UniverseManager._registry.universeById(id=id)
        if not universeInfo:
            raise ValueError(f'Unknown universe {id!r}')

        universePath = UniverseManager._universeDbFilePath(id=id)
        return multiverse.UniverseDb(universePath=universePath)

    def universeMilieu(self, id: str) -> str:
        universeInfo = UniverseManager._registry.universeById(id=id)
        if not universeInfo:
            raise ValueError(f'Unknown universe {id!r}')

        universePath = UniverseManager._universeDbFilePath(id=id)
        universeDb = multiverse.UniverseDb(universePath=universePath)
        return universeDb.milieu()

    # TODO: The progress messages generated by this are a bit of a mess now
    def createUniverse(
            self,
            name: str,
            milieu: str,
            description: str = '',
            importTravellerMap: bool = False,
            progress: typing.Optional[common.ProgressTracker] = None,
            reporter: typing.Optional[common.Reporter] = None
            ) -> str: # Universe Id
        if not name.strip():
            raise ValueError(f'Universe name can\'t be empty')

        taskWeight = None
        if progress is not None:
            taskCount = 2 # Load & Save
            taskWeight = 1 / taskCount

        dbAllegiances = dbSophonts = dbSectors = dbSystems = dbMapLabels = dbMapVectors = None
        if importTravellerMap:
            dbAllegiances, dbSophonts, dbSectors, dbSystems, dbMapLabels, dbMapVectors = \
                self._loadStockUniverse(
                    milieu=milieu,
                    progress=progress.createChild(weight=taskWeight) if progress is not None else None,
                    reporter=reporter)

        universeId = str(uuid.uuid4())
        universePath = UniverseManager._universeDbFilePath(id=universeId)
        if os.path.exists(universePath):
            raise RuntimeError(f'Universe database {universePath!r} already exists')

        universeDb = None
        try:
            # Always create database, even when there are no sectors, as we want it
            # to be created on disk
            universeDb = multiverse.UniverseDb(universePath=universePath)

            self._saveUniverse(
                universeDb=universeDb,
                milieu=milieu,
                description=description,
                dbAllegiances=dbAllegiances,
                dbSophonts=dbSophonts,
                dbSectors=dbSectors,
                dbSystems=dbSystems,
                dbMapLabels=dbMapLabels,
                dbMapVectors=dbMapVectors,
                progress=progress.createChild(weight=taskWeight) if progress is not None else None)

            # Only add the universe to the registry after the database has been
            # created to avoid dangling entries if creating the database fails
            UniverseManager._registry.addUniverse(id=universeId, name=name)
        except Exception:
            # Attempt to tidy up by deleting the universe database
            try:
                os.remove(universePath)
            except Exception as ex:
                logging.error(f'UniverseManager failed to clean up universe file {universePath!r}', exc_info=ex)
            raise

        return universeId

    def updateSectors(
                self,
                id: str,
                sectors: typing.Collection[multiverse.DbSector],
                progressCallback: typing.Optional[typing.Callable[[typing.Optional[str], int, int], typing.Any]] = None,
                ) -> str: # Universe Id
            universeInfo = UniverseManager._registry.universeById(id=id)
            if not universeInfo:
                raise ValueError(f'Unknown universe {id!r}')

            universePath = UniverseManager._universeDbFilePath(id=id)
            if not os.path.exists(universePath):
                raise RuntimeError(f'Universe database {universePath!r} already exists')

            if progressCallback:
                try:
                    progressCallback('Updating', 0, 0)
                except Exception as ex:
                    logging.warning('UniverseManager sector update progress callback threw an exception', exc_info=ex)

            # Always create database, even when there are no sectors, as we want it
            # to be created on disk
            universeDb = multiverse.UniverseDb(universePath=universePath)

            with universeDb.createTransaction() as transaction:
                sectorCount = len(sectors)
                for progressCount, sector in enumerate(sectors):
                    if progressCallback:
                        try:
                            progressCallback(
                                f'Updating: {sector.name()}',
                                progressCount,
                                sectorCount)
                        except Exception as ex:
                            logging.warning('UniverseManager sector update progress callback threw an exception', exc_info=ex)

                    universeDb.saveSectors(sectors=[sector], transaction=transaction)

            if progressCallback:
                try:
                    progressCallback('Updating: Complete!', 1, 1)
                except Exception as ex:
                    logging.warning('UniverseManager sector update progress callback threw an exception', exc_info=ex)

            return id

    def deleteUniverse(self, id: str) -> None:
        info = UniverseManager._registry.universeById(id=id)
        if info is None:
            raise ValueError(f'Universe {id!r} doesn\'t exist')

        UniverseManager._registry.removeUniverse(id=id)

        dbPath = UniverseManager._universeDbFilePath(id=id)
        if os.path.isfile(dbPath):
            os.remove(dbPath)

    def importUniverse(
            self,
            name: str,
            importPath: str
            ) -> str: # Universe ID
        if not name.strip():
            raise ValueError(f'Universe name can\'t be empty')

        if not multiverse.UniverseDb.isUniverseDb(universePath=importPath):
            raise ValueError(f'File {importPath!r} is not a universe database')

        universeId = str(uuid.uuid4())

        universePath = UniverseManager._universeDbFilePath(id=universeId)
        if os.path.exists(universePath):
            raise RuntimeError(f'Universe database {universePath!r} already exists')

        try:
            database.copyDatabase(
                src=importPath,
                dst=universePath)

            self._registry.addUniverse(id=universeId, name=name)
        except:
            if os.path.exists(universePath):
                os.remove(universePath)
            raise

        return universeId

    def exportUniverse(self, id: str, exportPath: str) -> None:
        info = UniverseManager._registry.universeById(id=id)
        if info is None:
            raise ValueError(f'Universe {id!r} doesn\'t exist')

        dbPath = UniverseManager._universeDbFilePath(id=id)

        database.copyDatabase(
            src=dbPath,
            dst=exportPath)

    def setUniverseName(
            self,
            id: str,
            name: str) -> None:
        if not name.strip():
            raise ValueError(f'Universe name can\'t be empty')

        info = UniverseManager._registry.universeById(id=id)
        if info is None:
            raise ValueError(f'Universe {id!r} doesn\'t exist')

        if info.name() == name:
            # The universe already has the specified name so nothing
            # to do
            return

        UniverseManager._registry.setUniverseName(id=id, name=name)

    def universeDescription(self, id: str) -> str:
        universeInfo = UniverseManager._registry.universeById(id=id)
        if not universeInfo:
            raise ValueError(f'Unknown universe {id!r}')

        dbPath = UniverseManager._universeDbFilePath(id=id)
        universeDb = multiverse.UniverseDb(universePath=dbPath)
        return universeDb.description()

    def setUniverseDescription(
            self,
            id: str,
            description: str
            ) -> None:
        universeInfo = UniverseManager._registry.universeById(id=id)
        if not universeInfo:
            raise ValueError(f'Unknown universe {id!r}')

        dbPath = UniverseManager._universeDbFilePath(id=id)
        universeDb = multiverse.UniverseDb(universePath=dbPath)
        universeDb.setDescription(description=description)

    def sectorInfos(
            self,
            id: str
            ) -> typing.List[multiverse.SectorInfo]:
        universeInfo = UniverseManager._registry.universeById(id=id)
        if not universeInfo:
            raise ValueError(f'Unknown universe {id!r}')

        dbPath = UniverseManager._universeDbFilePath(id=id)
        universeDb = multiverse.UniverseDb(universePath=dbPath)

        return universeDb.listSectors()

    def _loadStockUniverse(
            self,
            milieu: str,
            # TODO: Do something with progress
            progress: typing.Optional[common.ProgressTracker] = None,
            # TODO: Do something with the reporter
            reporter: typing.Optional[common.Reporter] = None
            ) -> typing.Tuple[
                typing.List[multiverse.DbAllegiance],
                typing.List[multiverse.DbSophont],
                typing.List[multiverse.DbSector],
                typing.List[multiverse.DbSystem],
                typing.List[multiverse.DbMapLabel],
                typing.List[multiverse.DbMapVector]]:
        if reporter:
            reporter.pushPrefix('Stock Allegiances: ')
        try:
            rawStockAllegiances = multiverse.loadSnapshotStockAllegiances(reporter=reporter)
        finally:
            if reporter:
                reporter.popPrefix()

        if reporter:
            reporter.pushPrefix('Stock Sophonts: ')
        try:
            rawStockSophonts = multiverse.loadSnapshotStockSophonts(reporter=reporter)
        finally:
            if reporter:
                reporter.popPrefix()

        if reporter:
            reporter.pushPrefix('Stock Style Sheet: ')
        try:
            rawStockStyleSheet = multiverse.loadSnapshotStyleSheet(reporter=reporter)
        finally:
            if reporter:
                reporter.popPrefix()

        if reporter:
            reporter.pushPrefix('Mega Labels: ')
        try:
            rawMegaLabels = multiverse.loadMegaLabels(reporter=reporter)
        finally:
            if reporter:
                reporter.popPrefix()

        if reporter:
            reporter.pushPrefix('Minor Labels: ')
        try:
            rawMinorLabels = multiverse.loadMinorLabels(reporter=reporter)
        finally:
            if reporter:
                reporter.popPrefix()

        if reporter:
            reporter.pushPrefix('World Labels: ')
        try:
            rawWorldLabels = multiverse.loadWorldLabels(reporter=reporter)
        finally:
            if reporter:
                reporter.popPrefix()

        if reporter:
            reporter.pushPrefix('Border Vectors: ')
        try:
            rawBorderVectors = multiverse.loadBorderVectors(reporter=reporter)
        finally:
            if reporter:
                reporter.popPrefix()

        if reporter:
            reporter.pushPrefix('Rift Vectors: ')
        try:
            rawRiftVectors = multiverse.loadRiftVectors(reporter=reporter)
        finally:
            if reporter:
                reporter.popPrefix()

        if reporter:
            reporter.pushPrefix('Route Vectors: ')
        try:
            rawRouteVectors = multiverse.loadRouteVectors(reporter=reporter)
        finally:
            if reporter:
                reporter.popPrefix()

        rawUniverseInfo = survey.parseUniverseInfo(
            content=multiverse.SnapshotManager.instance().readUniverseInfo(milieu=milieu))

        sectorNames = []
        for sectorInfo in rawUniverseInfo:
            nameInfos = sectorInfo.nameInfos()
            canonicalName = nameInfos[0].name() if nameInfos else None
            if not canonicalName:
                logging.warning(f'Stock universe import ignoring sector with no name in milieu {milieu}')
                continue
            sectorNames.append(canonicalName)

        localProgress = None
        if progress is not None:
            steps = len(sectorNames) + 4 # + 4 for each of the convert steps
            localProgress = progress.createChild(weight=1, steps=steps)

        rawSectors: typing.List[typing.Tuple[survey.RawMetadata, typing.List[survey.RawWorld]]] = []
        for sectorName in sectorNames:
            try:
                if reporter:
                    reporter.pushPrefix(f'{milieu} {sectorName} Metadata - ')
                try:
                    sectorMetadata = multiverse.SnapshotManager.instance().readSectorMetadata(
                        milieu=milieu,
                        sector=sectorName)
                    rawMetadata = survey.parseMetadata(content=sectorMetadata, reporter=reporter)
                finally:
                    if reporter:
                        reporter.popPrefix()

                if reporter:
                    reporter.pushPrefix(f'{milieu} {sectorName} Sector - ')
                try:
                    sectorContent = multiverse.SnapshotManager.instance().readSectorContent(
                        milieu=milieu,
                        sector=sectorName)
                    rawSystems = survey.parseSector(content=sectorContent, reporter=reporter)
                finally:
                    if reporter:
                        reporter.popPrefix()

                rawSectors.append((rawMetadata, rawSystems))
                if localProgress is not None:
                    localProgress.advance()
            except Exception as ex:
                logging.error(f'Stock universe import failed to load data for sector {sectorName} from {milieu}', exc_info=ex)

        styleMapper = multiverse.StyleMapper(
            rawSectors=rawSectors,
            rawStockStyleSheet=rawStockStyleSheet)
        allegianceMapper = multiverse.AllegianceMapper(
            milieu=milieu,
            rawSectors=rawSectors,
            rawStockAllegiances=rawStockAllegiances,
            styleMapper=styleMapper)
        sophontMapper = multiverse.SophontMapper(
            rawSectors=rawSectors,
            rawStockSophonts=rawStockSophonts)

        dbSectors = multiverse.convertRawSectorsToDbSectors(
            rawSectors=rawSectors,
            allegianceMapper=allegianceMapper,
            styleMapper=styleMapper)
        if localProgress is not None:
            localProgress.advance()

        dbSystems = multiverse.convertRawWorldsToDbSystems(
            rawSectors=rawSectors,
            allegianceMapper=allegianceMapper,
            sophontMapper=sophontMapper)
        if localProgress is not None:
            localProgress.advance()

        dbMapLabels: typing.List[multiverse.DbMapLabel] = []
        dbMapLabels.extend(multiverse.convertRawLabelsToDbMapLabels(
            rawMegaLabels=rawMegaLabels,
            rawMinorLabels=rawMinorLabels,
            rawWorldLabels=rawWorldLabels,
            rawUniverseInfo=rawUniverseInfo))
        if localProgress is not None:
            localProgress.advance()

        dbMapLabels.extend(multiverse.convertRawVectorsToDbMapLabels(
            rawBorderVectors=rawBorderVectors,
            rawRiftVectors=rawRiftVectors,
            rawRouteVectors=rawRouteVectors))
        if localProgress is not None:
            localProgress.advance()

        dbMapVectors: typing.List[multiverse.DbMapVector] = []
        dbMapVectors.extend(multiverse.convertRawVectorsToDbMapVectors(
            rawBorderVectors=rawBorderVectors,
            rawRiftVectors=rawRiftVectors,
            rawRouteVectors=rawRouteVectors))

        return (
            allegianceMapper.listAllegiances(),
            sophontMapper.listSophonts(),
            dbSectors,
            dbSystems,
            dbMapLabels,
            dbMapVectors)

    def _saveUniverse(
            self,
            universeDb: multiverse.UniverseDb,
            milieu: str,
            description: str,
            dbAllegiances: typing.Optional[typing.Collection[multiverse.DbAllegiance]],
            dbSophonts: typing.Optional[typing.Collection[multiverse.DbSophont]],
            dbSectors: typing.Optional[typing.Collection[multiverse.DbSector]],
            dbSystems: typing.Optional[typing.Collection[multiverse.DbSystem]],
            dbMapLabels: typing.Optional[typing.Collection[multiverse.DbMapLabel]],
            dbMapVectors: typing.Optional[typing.Collection[multiverse.DbMapVector]],
            progress: typing.Optional[common.ProgressTracker] = None
            ) -> None:
        objectCount = 0
        saveTasks = []
        if dbAllegiances:
            objectCount += len(dbAllegiances)
        if dbSophonts:
            objectCount += len(dbSophonts)
        if dbSectors:
            objectCount += len(dbSectors)
        if dbSystems:
            objectCount += len(dbSystems)
        if dbMapLabels:
            objectCount += len(dbMapLabels)
        if dbMapVectors:
            objectCount += len(dbMapLabels)

        saveTasks = []
        if dbAllegiances:
            saveTasks.append((dbAllegiances, universeDb.saveAllegiances, len(dbAllegiances) / objectCount))
        if dbSophonts:
            saveTasks.append((dbSophonts, universeDb.saveSophonts, len(dbSophonts) / objectCount))
        if dbSectors:
            saveTasks.append((dbSectors, universeDb.saveSectors, len(dbSectors) / objectCount))
        if dbSystems:
            saveTasks.append((dbSystems, universeDb.saveSystems, len(dbSystems) / objectCount))
        if dbMapLabels:
            saveTasks.append((dbMapLabels, universeDb.saveMapLabels, len(dbMapLabels) / objectCount))
        if dbMapVectors:
            saveTasks.append((dbMapVectors, universeDb.saveMapVectors, len(dbMapVectors) / objectCount))

        with universeDb.createTransaction() as transaction:
            universeDb.setMilieu(milieu=milieu, transaction=transaction)
            universeDb.setDescription(description=description, transaction=transaction)

            for objects, function, taskWeight in saveTasks:
                taskProgress = progress.createChild(weight=taskWeight) if progress is not None else None
                if objects:
                    function(
                        objects,
                        transaction=transaction,
                        progress=taskProgress)
                elif taskProgress is not None:
                    taskProgress.complete()

    @staticmethod
    def _registryDbFilePath() -> str:
        return os.path.join(
            UniverseManager._multiversePath,
            UniverseManager._RegistryFileName)

    @staticmethod
    def _universeDirPath() -> str:
        return os.path.join(
            UniverseManager._multiversePath,
            UniverseManager._UniversesDir)

    @staticmethod
    def _universeDbFilePath(id: str) -> str:
        return os.path.join(
            UniverseManager._universeDirPath(),
            f'{id}.db')