import common
import hashlib
import logging
import multiverse
import os
import survey
import threading
import typing
import uuid

# TODO: When updating snapshot I'll need to do something to make sure notes
# are preserved on systems/sectors. I could split notes in a separate table
# but it's probably easiest to just read the existing notes and set the
# notes on the new object before writing it to the db.
# TODO: When I switch to making a copy of the entire universe for custom
# universes, I need to add an option to regenerate the trade codes for
# the entire universe based on a specified rule set. It should default to
# the current selected rules but also have the option to use the trade
# codes as they appear on Traveller Map (explain the difference in a tooltip).
# The default universe will always use the Traveller Map trade codes.
# This will replace the ability to switch between modes dynamically which
# I removed as it complicated the code for generating remarks.
# Part of this work will probably need to be converting calculateMongooseTradeCodes
# to use string trade codes rather than traveller.TradeCode as the converter
# code doesn't have access to that logic.
# Alternatively it might be the time to convert DbObjects to use enums for things.
# It would make sense if it was the same ones as the traveller/astronomer code, so
# maybe I need some kind of low level basic type namespace.
# I've left the _RegenerateTradeCodesToolTip text as it could be a basis for the
# option when I add it to the custom universe creation dialog
# TODO: Top level functions should log that they were called

class UniverseManager(object):
    _RegistryFileName = 'registry.db'
    _UniversesDir = 'universes'

    _StockUniverseName = 'Traveller Map'
    _StockUniverseDescription = 'Sector data taken from Traveller Map'

    _lock = threading.RLock() # Recursive lock
    _instance = None # Singleton instance
    _initialised = False
    _multiversePath = None
    _registry = None

    def __init__(self) -> None:
        raise RuntimeError('Call instance() instead')

    @classmethod
    def instance(cls):
        if not cls._instance:
            with cls._lock:
                # Recheck instance as another thread could have created it between the
                # first check adn the lock
                if not cls._instance:
                    cls._instance = cls.__new__(cls)
        return cls._instance

    @staticmethod
    def initialise(
            multiversePath: str
            ) -> None:
        if UniverseManager._initialised:
            raise RuntimeError('The MultiverseDb singleton has already been initialised')

        UniverseManager._multiversePath = multiversePath

        universePath = UniverseManager._universeDirPath()
        os.makedirs(universePath, exist_ok=True)

        registryPath = UniverseManager._registryDbFilePath()
        UniverseManager._registry = multiverse.UniverseRegistry(registryPath=registryPath)

        UniverseManager._initialised = True

    def universeInfos(self) -> typing.List[multiverse.UniverseInfo]:
        return UniverseManager._registry.listUniverses()

    def universeInfoById(self, id: str) -> typing.Optional[multiverse.UniverseInfo]:
        return UniverseManager._registry.universeById(id=id)

    def universeInfoByName(self, name: str) -> typing.Optional[multiverse.UniverseInfo]:
        return UniverseManager._registry.universeByName(name=name)

    # TODO: The progress messages generated by this are a bit of a mess now
    def createUniverse(
            self,
            name: str,
            milieu: str,
            description: str,
            importTravellerMap: bool,
            progressCallback: typing.Optional[typing.Callable[[str, int, int], typing.Any]] = None,
            reporter: typing.Optional[common.Reporter] = None
            ) -> str: # Universe Id
        if self.universeInfoByName(name) is not None:
            raise ValueError(f'A Universe named {name!r} already exists')

        dbSectors: typing.List[multiverse.DbSector] = []
        if importTravellerMap:
            if reporter:
                reporter.pushPrefix('Stock Allegiances: ')
            try:
                rawStockAllegiances = multiverse.loadSnapshotStockAllegiances(reporter=reporter)
            finally:
                if reporter:
                    reporter.popPrefix()

            if reporter:
                reporter.pushPrefix('Stock Sophonts: ')
            try:
                rawStockSophonts = multiverse.loadSnapshotStockSophonts(reporter=reporter)
            finally:
                if reporter:
                    reporter.popPrefix()

            if reporter:
                reporter.pushPrefix('Stock Style Sheet: ')
            try:
                rawStockStyleSheet = multiverse.loadSnapshotStyleSheet(reporter=reporter)
            finally:
                if reporter:
                    reporter.popPrefix()

            rawUniverseInfo = survey.parseUniverseInfo(
                content=multiverse.SnapshotManager.instance().readUniverseInfo(milieu=milieu))

            sectorNames = []
            for sectorInfo in rawUniverseInfo.sectorInfos():
                nameInfos = sectorInfo.nameInfos()
                canonicalName = nameInfos[0].name() if nameInfos else None
                if not canonicalName:
                    logging.warning(f'Stock universe import ignoring sector with no name in milieu {milieu}')
                    continue
                sectorNames.append(canonicalName)

            sourceDataHashes: typing.Dict[multiverse.DbSector, str] = {}
            progressCount = 0
            for sectorName in sectorNames:
                if progressCallback:
                    try:
                        progressCallback(
                            f'Converting: {milieu} - {sectorName}',
                            progressCount,
                            len(sectorNames))
                        progressCount += 1
                    except Exception as ex:
                        logging.warning('Stock universe import progress callback threw an exception', exc_info=ex)

                try:
                    if reporter:
                        reporter.pushPrefix(f'{milieu} {sectorName} Metadata - ')
                    try:
                        sectorMetadata = multiverse.SnapshotManager.instance().readSectorMetadata(
                            milieu=milieu,
                            sector=sectorName)
                        rawMetadata = survey.parseMetadata(content=sectorMetadata, reporter=reporter)
                    finally:
                        if reporter:
                            reporter.popPrefix()

                    if reporter:
                        reporter.pushPrefix(f'{milieu} {sectorName} Sector - ')
                    try:
                        sectorContent = multiverse.SnapshotManager.instance().readSectorContent(
                            milieu=milieu,
                            sector=sectorName)
                        rawSystems = survey.parseSector(content=sectorContent, reporter=reporter)
                    finally:
                        if reporter:
                            reporter.popPrefix()

                    dbSector = multiverse.convertRawSectorToDbSector(
                        milieu=milieu,
                        rawMetadata=rawMetadata,
                        rawSystems=rawSystems,
                        rawStockAllegiances=rawStockAllegiances,
                        rawStockSophonts=rawStockSophonts,
                        rawStockStyleSheet=rawStockStyleSheet)
                    dbSectors.append(dbSector)

                    # TODO: I'm not doing anything with these hashes at the moment, need to push them
                    # to the DB
                    hash = hashlib.sha256()
                    hash.update(hashlib.sha256(sectorMetadata.encode()).digest())
                    hash.update(hashlib.sha256(sectorContent.encode()).digest())
                    sourceDataHashes[dbSector] = hash.hexdigest()
                except Exception as ex:
                    logging.error(f'Stock universe import failed to load data for sector {sectorName} from {milieu}', exc_info=ex)

            if progressCallback:
                try:
                    progressCallback(
                        f'Converting: Complete!',
                        len(sectorNames),
                        len(sectorNames))
                except Exception as ex:
                    logging.warning('Stock universe import progress callback threw an exception', exc_info=ex)

        universeId = str(uuid.uuid4())
        universePath = UniverseManager._universeDbFilePath(id=universeId)
        if os.path.exists(universePath):
            raise RuntimeError(f'Universe database {universePath!r} already exists')

        if progressCallback:
            try:
                progressCallback('Creating', 0, 0)
            except Exception as ex:
                logging.warning('UniverseManager custom universe creation progress callback threw an exception', exc_info=ex)

        # Always create database, even when there are no sectors, as we want it
        # to be created on disk
        universeDb = multiverse.UniverseDb(universePath=universePath)

        if dbSectors:
            with universeDb.createTransaction() as transaction:
                sectorCount = len(dbSectors)
                for progressCount, sector in enumerate(dbSectors):
                    if progressCallback:
                        try:
                            progressCallback(
                                f'Creating: {sector.name()}',
                                progressCount,
                                sectorCount)
                        except Exception as ex:
                            logging.warning('UniverseManager custom universe creation progress callback threw an exception', exc_info=ex)

                    universeDb.saveSector(sector=sector, transaction=transaction)

        # Only add the universe to the registry after the database has been
        # created to avoid dangling entries if creating the database fails
        try:
            UniverseManager._registry.addUniverse(
                id=universeId,
                name=name,
                description=description)
        except Exception:
            # Attempt to tidy up by deleting the universe database
            try:
                os.remove(universePath)
            except Exception as ex:
                logging.error(f'UniverseManager failed to clean up universe file {universePath!r}', exc_info=ex)
            raise

        if progressCallback:
            try:
                progressCallback('Creation: Complete!', 1, 1)
            except Exception as ex:
                logging.warning('UniverseManager custom universe creation progress callback threw an exception', exc_info=ex)

        return universeId

    def updateSectors(
                self,
                universeId: str,
                sectors: typing.Collection[multiverse.DbSector],
                progressCallback: typing.Optional[typing.Callable[[typing.Optional[str], int, int], typing.Any]] = None,
                ) -> str: # Universe Id
            universeInfo = UniverseManager._registry.universeById(id=universeId)
            if not universeInfo:
                raise ValueError(f'Unknown universe {universeId!r}')

            universePath = UniverseManager._universeDbFilePath(id=universeId)
            if not os.path.exists(universePath):
                raise RuntimeError(f'Universe database {universePath!r} already exists')

            if progressCallback:
                try:
                    progressCallback('Updating', 0, 0)
                except Exception as ex:
                    logging.warning('UniverseManager sector update progress callback threw an exception', exc_info=ex)

            # Always create database, even when there are no sectors, as we want it
            # to be created on disk
            universeDb = multiverse.UniverseDb(universePath=universePath)

            with universeDb.createTransaction() as transaction:
                sectorCount = len(sectors)
                for progressCount, sector in enumerate(sectors):
                    if progressCallback:
                        try:
                            progressCallback(
                                f'Updating: {sector.name()}',
                                progressCount,
                                sectorCount)
                        except Exception as ex:
                            logging.warning('UniverseManager sector update progress callback threw an exception', exc_info=ex)

                    universeDb.saveSector(sector=sector, transaction=transaction)

            if progressCallback:
                try:
                    progressCallback('Updating: Complete!', 1, 1)
                except Exception as ex:
                    logging.warning('UniverseManager sector update progress callback threw an exception', exc_info=ex)

            return universeId

    def deleteUniverse(self, universeId: str) -> None:
        info = UniverseManager._registry.universeById(id=universeId)
        if info is None:
            raise ValueError(f'Universe {universeId!r} doesn\'t exist')

        UniverseManager._registry.removeUniverse(id=universeId)

        dbPath = UniverseManager._universeDbFilePath(id=universeId)
        if os.path.isfile(dbPath):
            os.remove(dbPath)

    def setUniverseName(
            self,
            universeId: str,
            name: str) -> None:
        info = UniverseManager._registry.universeByName(name=name)
        if info:
            if info.id() == universeId:
                # There is no change in name so nothing to do
                return

            # There is already a universe with the same name
            raise ValueError(f'Universe named {name!r} already exists')

        UniverseManager._registry.setUniverseName(id=universeId, name=name)

    def setUniverseDescription(
            self,
            id: str,
            description: str
            ) -> None:
        UniverseManager._registry.setUniverseDescription(id=id, description=description)

    def sectorInfos(
            self,
            universeId: str
            ) -> typing.List[multiverse.SectorInfo]:
        universeInfo = UniverseManager._registry.universeById(id=universeId)
        if not universeInfo:
            raise ValueError(f'Unknown universe {universeId!r}')

        dbPath = UniverseManager._universeDbFilePath(id=universeId)
        universeDb = multiverse.UniverseDb(universePath=dbPath)

        return universeDb.listSectors()

    def sectors(
            self,
            universeId: str,
            progressCallback: typing.Optional[typing.Callable[[typing.Optional[str], int, int], typing.Any]] = None
            ) -> typing.List[multiverse.DbSector]:
        return list(self.yieldSectors(universeId=universeId, progressCallback=progressCallback))

    def yieldSectors(
            self,
            universeId: str,
            progressCallback: typing.Optional[typing.Callable[[typing.Optional[str], int, int], typing.Any]] = None
            ) -> typing.Generator[multiverse.DbSector, None, None]:
        universeInfo = UniverseManager._registry.universeById(id=universeId)
        if not universeInfo:
            raise ValueError(f'Unknown universe {universeId!r}')

        dbPath = UniverseManager._universeDbFilePath(id=universeId)
        universeDb = multiverse.UniverseDb(universePath=dbPath)

        with universeDb.createTransaction() as transaction:
            sectorInfos = universeDb.listSectors(transaction=transaction)
            sectorCount = len(sectorInfos)
            for progressCount, sectorInfo in enumerate(sectorInfos):
                if progressCallback:
                    try:
                        progressCallback(
                            f'Loading: {sectorInfo.name()}',
                            progressCount,
                            sectorCount)
                    except Exception as ex:
                        logging.warning('UniverseManager universe read progress callback threw an exception', exc_info=ex)

                try:
                    sector = universeDb.loadSector(
                        sectorId=sectorInfo.id(),
                        transaction=transaction)
                    yield sector
                except Exception as ex:
                    # Log error but continue loading
                    logging.error(f'UniverseManager failed to read sector {sectorInfo.id()!r}', exc_info=ex)

            if progressCallback:
                try:
                    progressCallback(
                        f'Loading: Complete!',
                        sectorCount,
                        sectorCount)
                except Exception as ex:
                    logging.warning('UniverseManager universe read progress callback threw an exception', exc_info=ex)

    @staticmethod
    def _registryDbFilePath() -> str:
        return os.path.join(
            UniverseManager._multiversePath,
            UniverseManager._RegistryFileName)

    @staticmethod
    def _universeDirPath() -> str:
        return os.path.join(
            UniverseManager._multiversePath,
            UniverseManager._UniversesDir)

    @staticmethod
    def _universeDbFilePath(id: str) -> str:
        return os.path.join(
            UniverseManager._universeDirPath(),
            f'{id}.db')