import common
import database
import hashlib
import logging
import multiverse
import os
import survey
import threading
import typing
import uuid

# TODO: When updating snapshot I'll need to do something to make sure notes
# are preserved on systems/sectors. I could split notes in a separate table
# but it's probably easiest to just read the existing notes and set the
# notes on the new object before writing it to the db.
# TODO: When I switch to making a copy of the entire universe for custom
# universes, I need to add an option to regenerate the trade codes for
# the entire universe based on a specified rule set. It should default to
# the current selected rules but also have the option to use the trade
# codes as they appear on Traveller Map (explain the difference in a tooltip).
# The default universe will always use the Traveller Map trade codes.
# This will replace the ability to switch between modes dynamically which
# I removed as it complicated the code for generating remarks.
# Part of this work will probably need to be converting calculateMongooseTradeCodes
# to use string trade codes rather than traveller.TradeCode as the converter
# code doesn't have access to that logic.
# Alternatively it might be the time to convert DbObjects to use enums for things.
# It would make sense if it was the same ones as the traveller/astronomer code, so
# maybe I need some kind of low level basic type namespace.
# I've left the _RegenerateTradeCodesToolTip text as it could be a basis for the
# option when I add it to the custom universe creation dialog
# TODO: Top level functions should log that they were called

class UniverseInfo(object):
    def __init__(
            self,
            id: str,
            name: str,
            description: str
            ) -> None:
        common.validateStr(name='id', value=id, allowEmpty=False)
        common.validateStr(name='name', value=name, allowEmpty=False)
        common.validateStr(name='description', value=description, allowEmpty=True)

        self._id = id
        self._name = name
        self._description = description

    def id(self) -> str:
        return self._id

    def name(self) -> str:
        return self._name

    def description(self) -> str:
        return self._description

class UniverseManager(object):
    _RegistryFileName = 'registry.db'
    _UniversesDir = 'universes'

    _StockUniverseName = 'Traveller Map'
    _StockUniverseDescription = 'Sector data taken from Traveller Map'

    _lock = threading.RLock() # Recursive lock
    _instance = None # Singleton instance
    _initialised = False
    _multiversePath = None
    _registry = None

    def __init__(self) -> None:
        raise RuntimeError('Call instance() instead')

    @classmethod
    def instance(cls):
        if not cls._instance:
            with cls._lock:
                # Recheck instance as another thread could have created it between the
                # first check adn the lock
                if not cls._instance:
                    cls._instance = cls.__new__(cls)
        return cls._instance

    @staticmethod
    def initialise(
            multiversePath: str
            ) -> None:
        if UniverseManager._initialised:
            raise RuntimeError('The MultiverseDb singleton has already been initialised')

        UniverseManager._multiversePath = multiversePath

        universePath = UniverseManager._universeDirPath()
        os.makedirs(universePath, exist_ok=True)

        registryPath = UniverseManager._registryDbFilePath()
        UniverseManager._registry = multiverse.UniverseRegistry(registryPath=registryPath)

        UniverseManager._initialised = True

    def universeInfos(self) -> typing.List[multiverse.UniverseInfo]:
        return UniverseManager._registry.listUniverses()

    def universeInfoById(self, id: str) -> typing.Optional[multiverse.UniverseInfo]:
        return UniverseManager._registry.universeById(id=id)

    def universeMilieu(self, id: str) -> str:
        universeInfo = UniverseManager._registry.universeById(id=id)
        if not universeInfo:
            raise ValueError(f'Unknown universe {id!r}')

        universePath = UniverseManager._universeDbFilePath(id=id)
        universeDb = multiverse.UniverseDb(universePath=universePath)
        return universeDb.milieu()

    # TODO: The progress messages generated by this are a bit of a mess now
    def createUniverse(
            self,
            name: str,
            milieu: str,
            description: str = '',
            importTravellerMap: bool = False,
            progressCallback: typing.Optional[typing.Callable[[str, int, int], typing.Any]] = None,
            reporter: typing.Optional[common.Reporter] = None
            ) -> str: # Universe Id
        if not name.strip():
            raise ValueError(f'Universe name can\'t be empty')

        dbAllegiances = dbSectors = dbMapLabels = dbMapVectors = None
        if importTravellerMap:
            dbAllegiances, dbSectors, dbMapLabels, dbMapVectors = multiverse.convertStockUniverseToDbUniverse(
                milieu=milieu,
                progressCallback=progressCallback,
                reporter=reporter)

        universeId = str(uuid.uuid4())
        universePath = UniverseManager._universeDbFilePath(id=universeId)
        if os.path.exists(universePath):
            raise RuntimeError(f'Universe database {universePath!r} already exists')

        if progressCallback:
            try:
                progressCallback('Creating', 0, 0)
            except Exception as ex:
                logging.warning('UniverseManager custom universe creation progress callback threw an exception', exc_info=ex)

        # Always create database, even when there are no sectors, as we want it
        # to be created on disk
        universeDb = multiverse.UniverseDb(universePath=universePath)

        with universeDb.createTransaction() as transaction:
            universeDb.setMilieu(milieu=milieu, transaction=transaction)
            universeDb.setDescription(description=description, transaction=transaction)

            if dbAllegiances:
                for dbAllegiance in dbAllegiances:
                    universeDb.saveAllegiance(
                        allegiance=dbAllegiance,
                        transaction=transaction)

            if dbSectors:
                sectorCount = len(dbSectors)
                for progressCount, dbSector in enumerate(dbSectors):
                    if progressCallback:
                        try:
                            progressCallback(
                                f'Creating: {dbSector.name()}',
                                progressCount,
                                sectorCount)
                        except Exception as ex:
                            logging.warning('UniverseManager custom universe creation progress callback threw an exception', exc_info=ex)

                    universeDb.saveSector(
                        sector=dbSector,
                        # TODO: Need to re-add support for data hash
                        #stockDataHash=dataHash,
                        transaction=transaction)

            if dbMapLabels:
                for dbLabel in dbMapLabels:
                    universeDb.saveMapLabel(
                        label=dbLabel,
                        transaction=transaction)

            if dbMapVectors:
                for dbVector in dbMapVectors:
                    universeDb.saveMapVector(
                        vector=dbVector,
                        transaction=transaction)

        # Only add the universe to the registry after the database has been
        # created to avoid dangling entries if creating the database fails
        try:
            UniverseManager._registry.addUniverse(id=universeId, name=name)
        except Exception:
            # Attempt to tidy up by deleting the universe database
            try:
                os.remove(universePath)
            except Exception as ex:
                logging.error(f'UniverseManager failed to clean up universe file {universePath!r}', exc_info=ex)
            raise

        if progressCallback:
            try:
                progressCallback('Creation: Complete!', 1, 1)
            except Exception as ex:
                logging.warning('UniverseManager custom universe creation progress callback threw an exception', exc_info=ex)

        return universeId

    def updateSectors(
                self,
                id: str,
                sectors: typing.Collection[multiverse.DbSector],
                progressCallback: typing.Optional[typing.Callable[[typing.Optional[str], int, int], typing.Any]] = None,
                ) -> str: # Universe Id
            universeInfo = UniverseManager._registry.universeById(id=id)
            if not universeInfo:
                raise ValueError(f'Unknown universe {id!r}')

            universePath = UniverseManager._universeDbFilePath(id=id)
            if not os.path.exists(universePath):
                raise RuntimeError(f'Universe database {universePath!r} already exists')

            if progressCallback:
                try:
                    progressCallback('Updating', 0, 0)
                except Exception as ex:
                    logging.warning('UniverseManager sector update progress callback threw an exception', exc_info=ex)

            # Always create database, even when there are no sectors, as we want it
            # to be created on disk
            universeDb = multiverse.UniverseDb(universePath=universePath)

            with universeDb.createTransaction() as transaction:
                sectorCount = len(sectors)
                for progressCount, sector in enumerate(sectors):
                    if progressCallback:
                        try:
                            progressCallback(
                                f'Updating: {sector.name()}',
                                progressCount,
                                sectorCount)
                        except Exception as ex:
                            logging.warning('UniverseManager sector update progress callback threw an exception', exc_info=ex)

                    universeDb.saveSector(sector=sector, transaction=transaction)

            if progressCallback:
                try:
                    progressCallback('Updating: Complete!', 1, 1)
                except Exception as ex:
                    logging.warning('UniverseManager sector update progress callback threw an exception', exc_info=ex)

            return id

    def deleteUniverse(self, id: str) -> None:
        info = UniverseManager._registry.universeById(id=id)
        if info is None:
            raise ValueError(f'Universe {id!r} doesn\'t exist')

        UniverseManager._registry.removeUniverse(id=id)

        dbPath = UniverseManager._universeDbFilePath(id=id)
        if os.path.isfile(dbPath):
            os.remove(dbPath)

    def importUniverse(
            self,
            name: str,
            importPath: str
            ) -> str: # Universe ID
        if not name.strip():
            raise ValueError(f'Universe name can\'t be empty')

        if not multiverse.UniverseDb.isUniverseDb(universePath=importPath):
            raise ValueError(f'File {importPath!r} is not a universe database')

        universeId = str(uuid.uuid4())

        universePath = UniverseManager._universeDbFilePath(id=universeId)
        if os.path.exists(universePath):
            raise RuntimeError(f'Universe database {universePath!r} already exists')

        try:
            database.copyDatabase(
                src=importPath,
                dst=universePath)

            self._registry.addUniverse(id=universeId, name=name)
        except:
            if os.path.exists(universePath):
                os.remove(universePath)
            raise

        return universeId

    def exportUniverse(self, id: str, exportPath: str) -> None:
        info = UniverseManager._registry.universeById(id=id)
        if info is None:
            raise ValueError(f'Universe {id!r} doesn\'t exist')

        dbPath = UniverseManager._universeDbFilePath(id=id)

        database.copyDatabase(
            src=dbPath,
            dst=exportPath)

    def setUniverseName(
            self,
            id: str,
            name: str) -> None:
        if not name.strip():
            raise ValueError(f'Universe name can\'t be empty')

        info = UniverseManager._registry.universeById(id=id)
        if info is None:
            raise ValueError(f'Universe {id!r} doesn\'t exist')

        if info.name() == name:
            # The universe already has the specified name so nothing
            # to do
            return

        UniverseManager._registry.setUniverseName(id=id, name=name)

    def universeDescription(self, id: str) -> str:
        universeInfo = UniverseManager._registry.universeById(id=id)
        if not universeInfo:
            raise ValueError(f'Unknown universe {id!r}')

        dbPath = UniverseManager._universeDbFilePath(id=id)
        universeDb = multiverse.UniverseDb(universePath=dbPath)
        return universeDb.description()

    def setUniverseDescription(
            self,
            id: str,
            description: str
            ) -> None:
        universeInfo = UniverseManager._registry.universeById(id=id)
        if not universeInfo:
            raise ValueError(f'Unknown universe {id!r}')

        dbPath = UniverseManager._universeDbFilePath(id=id)
        universeDb = multiverse.UniverseDb(universePath=dbPath)
        universeDb.setDescription(description=description)

    def sectorInfos(
            self,
            id: str
            ) -> typing.List[multiverse.SectorInfo]:
        universeInfo = UniverseManager._registry.universeById(id=id)
        if not universeInfo:
            raise ValueError(f'Unknown universe {id!r}')

        dbPath = UniverseManager._universeDbFilePath(id=id)
        universeDb = multiverse.UniverseDb(universePath=dbPath)

        return universeDb.listSectors()

    def sectors(
            self,
            id: str,
            progressCallback: typing.Optional[typing.Callable[[typing.Optional[str], int, int], typing.Any]] = None
            ) -> typing.List[multiverse.DbSector]:
        return list(self.yieldSectors(id=id, progressCallback=progressCallback))

    def yieldSectors(
            self,
            id: str,
            progressCallback: typing.Optional[typing.Callable[[typing.Optional[str], int, int], typing.Any]] = None
            ) -> typing.Generator[multiverse.DbSector, None, None]:
        universeInfo = UniverseManager._registry.universeById(id=id)
        if not universeInfo:
            raise ValueError(f'Unknown universe {id!r}')

        dbPath = UniverseManager._universeDbFilePath(id=id)
        universeDb = multiverse.UniverseDb(universePath=dbPath)

        with universeDb.createTransaction() as transaction:
            sectorInfos = universeDb.listSectors(transaction=transaction)
            sectorCount = len(sectorInfos)
            for progressCount, sectorInfo in enumerate(sectorInfos):
                if progressCallback:
                    try:
                        progressCallback(
                            f'Loading: {sectorInfo.name()}',
                            progressCount,
                            sectorCount)
                    except Exception as ex:
                        logging.warning('UniverseManager universe read progress callback threw an exception', exc_info=ex)

                try:
                    sector = universeDb.loadSector(
                        sectorId=sectorInfo.id(),
                        transaction=transaction)
                    yield sector
                except Exception as ex:
                    # Log error but continue loading
                    logging.error(f'UniverseManager failed to read sector {sectorInfo.id()!r}', exc_info=ex)

            if progressCallback:
                try:
                    progressCallback(
                        f'Loading: Complete!',
                        sectorCount,
                        sectorCount)
                except Exception as ex:
                    logging.warning('UniverseManager universe read progress callback threw an exception', exc_info=ex)

    def allegiances(self, id: str) -> typing.List[multiverse.DbAllegiance]:
        universeInfo = UniverseManager._registry.universeById(id=id)
        if not universeInfo:
            raise ValueError(f'Unknown universe {id!r}')

        dbPath = UniverseManager._universeDbFilePath(id=id)
        universeDb = multiverse.UniverseDb(universePath=dbPath)

        with universeDb.createTransaction() as transaction:
            return universeDb.loadAllegiances(transaction=transaction)

    def mapLabels(self, id: str) -> typing.List[multiverse.DbMapLabel]:
        universeInfo = UniverseManager._registry.universeById(id=id)
        if not universeInfo:
            raise ValueError(f'Unknown universe {id!r}')

        dbPath = UniverseManager._universeDbFilePath(id=id)
        universeDb = multiverse.UniverseDb(universePath=dbPath)

        with universeDb.createTransaction() as transaction:
            return universeDb.loadMapLabels(transaction=transaction)

    def mapVectors(self, id: str) -> typing.List[multiverse.DbMapVector]:
        universeInfo = UniverseManager._registry.universeById(id=id)
        if not universeInfo:
            raise ValueError(f'Unknown universe {id!r}')

        dbPath = UniverseManager._universeDbFilePath(id=id)
        universeDb = multiverse.UniverseDb(universePath=dbPath)

        with universeDb.createTransaction() as transaction:
            return universeDb.loadMapVectors(transaction=transaction)

    @staticmethod
    def _registryDbFilePath() -> str:
        return os.path.join(
            UniverseManager._multiversePath,
            UniverseManager._RegistryFileName)

    @staticmethod
    def _universeDirPath() -> str:
        return os.path.join(
            UniverseManager._multiversePath,
            UniverseManager._UniversesDir)

    @staticmethod
    def _universeDbFilePath(id: str) -> str:
        return os.path.join(
            UniverseManager._universeDirPath(),
            f'{id}.db')