from .attribute import *
from .construction import *
from .step import *
from .component import *
from .robot import *
from .components.chassis import *
from .components.locomotion import *
from .components.armour import *
from .components.endurance import *
from .components.resiliency import *
from .components.agility import *
from .components.speed import *
from .components.manipulators import *
from .components.slotoptions import *
from .components.weapons import *
