import enum
import traveller
import typing

class StockWeaponSet(enum.Enum):
    Core2 = 'Core Rules 2e'
    Core2022 = 'Core Rules 2022'
    CSC2 = 'Central Supply Catalogue 2e'
    CSC2023 = 'Central Supply Catalogue 2023'

_CoreCompatible = [StockWeaponSet.Core2, StockWeaponSet.Core2022]
_SupplyCatalogueCompatible = [StockWeaponSet.CSC2, StockWeaponSet.CSC2023]
_AllCompatible = _CoreCompatible + _SupplyCatalogueCompatible

class WeaponSize(enum.Enum):
    Small = 'Small'
    Medium = 'Medium'
    Heavy = 'Heavy'
    Vehicle = 'Vehicle'

class StockWeapon(object):
    def __init__(
            self,
            name: str,
            techLevel: int,
            size: WeaponSize,
            skill: traveller.SkillDefinition,
            specialty: typing.Optional[enum.Enum] = None,
            cost: typing.Optional[int] = None,
            range: typing.Optional[float] = None,
            magazineSize: typing.Optional[int] = None,
            magazineCost: typing.Optional[int] = None,
            damage: typing.Union[str] = '',
            traits: typing.Union[str] = '',
            multiLink: bool = False,
            ) -> None:
        self._name = name
        self._techLevel = techLevel
        self._size = size
        self._skill = skill
        self._specialty = specialty
        self._cost = cost
        self._range = range
        self._magazineSize = magazineSize
        self._magazineCost = magazineCost
        self._damage = damage
        self._traits = traits
        self._multiLink = multiLink

    def name(self) -> str:
        return self._name
    
    def techLevel(self) -> int:
        return self._techLevel
        
    def size(self) -> int:
        return self._size
    
    def skill(self) -> traveller.SkillDefinition:
        return self._skill
    
    def specialty(self) -> typing.Optional[enum.Enum]:
        return self._specialty
    
    def cost(self) -> int:
        return self._cost

    def range(self) -> typing.Optional[float]:
        return self._range
    
    def magazineSize(self) -> typing.Optional[int]:
        return self._magazineSize

    def magazineCost(self) -> typing.Optional[int]:
        return self._magazineCost
            
    def damage(self) -> str:
        return self._damage
        
    def traits(self) -> str:
        return self._traits
    
    def multiLink(self) -> bool:
        return self._multiLink        

class _StockWeaponDescription(object):
    def __init__(
            self,
            name: str,
            techLevel: typing.Union[int, typing.Mapping[StockWeaponSet, int]],
            size: WeaponSize,
            skill: traveller.SkillDefinition,
            specialty: typing.Optional[enum.Enum] = None,
            cost: typing.Optional[typing.Union[int, typing.Mapping[StockWeaponSet, int]]] = None,
            range: typing.Optional[typing.Union[float, typing.Mapping[StockWeaponSet, float]]] = None,
            magazineSize: typing.Optional[typing.Union[int, typing.Mapping[StockWeaponSet, int]]] = None,
            magazineCost: typing.Optional[typing.Union[int, typing.Mapping[StockWeaponSet, int]]] = None,
            damage: typing.Union[str, typing.Mapping[StockWeaponSet, str]] = '',
            traits: typing.Union[str, typing.Mapping[StockWeaponSet, str]] = '',
            compatible: typing.Optional[typing.Iterable[StockWeaponSet]] = None,
            multiLink: bool = False,
            ) -> None:
        self._name = name
        self._techLevel = techLevel
        self._size = size
        self._skill = skill
        self._specialty = specialty
        self._cost = cost
        self._range = range
        self._magazineSize = magazineSize
        self._magazineCost = magazineCost
        self._damage = damage
        self._traits = traits
        self._compatible = compatible
        self._multiLink = multiLink

    def name(self) -> str:
        return self._name
    
    def isCompatible(
            self,
            weaponSet: StockWeaponSet
            ) -> bool:
        return not self._compatible or weaponSet in self._compatible        
    
    def createStockWeapon(
            self,
            weaponSet: StockWeaponSet
            ) -> typing.Optional[StockWeapon]:
        if self._compatible and weaponSet not in self._compatible:
            return None
        
        return StockWeapon(
            name=self._name,
            techLevel=self._techLevel[weaponSet] if isinstance(self._techLevel, dict) else self._techLevel,
            size=self._size,
            skill=self._skill,
            specialty=self._specialty,
            cost=self._cost[weaponSet] if isinstance(self._cost, dict) else self._cost,
            range=self._range[weaponSet] if isinstance(self._range, dict) else self._range,
            magazineSize=self._magazineSize[weaponSet] if isinstance(self._magazineSize, dict) else self._magazineSize,
            magazineCost=self._magazineCost[weaponSet] if isinstance(self._magazineCost, dict) else self._magazineCost,
            damage=self._damage[weaponSet] if isinstance(self._damage, dict) else self._damage,
            traits=self._traits[weaponSet] if isinstance(self._traits, dict) else self._traits,
            multiLink=self._multiLink)
        
    
# List of weapons taken from the MGT2 Robot Worksheet v1.50.01 spreadsheet
# IMPORTANT: These weapon names MUST remain constant between versions otherwise
# it will break weapons saved by older versions
# NOTE: Based on some of the weapons on the list (pepper spray, some of the
# grenades etc) I think this is the list of weapons from the 2023 update of the
# companion
# NOTE: The multilink flag that some weapons have come from the spreadsheet.
# I've not found anything that would indicate it's official but it does seem to
# have some logic behind it. As far as I can tell it's generally weapons that
# are fired rather than wielded or thrown, although there are a few exceptions
# (notably launchers).
# I've kept the value here for completeness but I don't plan to use it. I don't
# see why you couldn't have a multi-linked melee weapon for example. I think
# it's best to allow any weapon to be multi-linked and leave it up to referees
# to say if it's allowed.
_WeaponDescriptions = [
    _StockWeaponDescription(
        name='Aerosol Grenade',
        size=WeaponSize.Small,
        skill=traveller.AthleticsSkillDefinition,
        specialty=traveller.AthleticsSkillSpecialities.Dexterity,
        techLevel=9,
        cost=15,
        range=20,
        traits='Blast 9',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Chemical Grenade', # NOTE: Not in original CSC
        size=WeaponSize.Small,
        skill=traveller.AthleticsSkillDefinition,
        specialty=traveller.AthleticsSkillSpecialities.Dexterity,
        techLevel=5,
        cost=50,
        range=20,
        damage='Special',
        traits='Blast 9',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='EMP Grenade',
        size=WeaponSize.Small,
        skill=traveller.AthleticsSkillDefinition,
        specialty=traveller.AthleticsSkillSpecialities.Dexterity,
        techLevel=9,
        cost=100,
        range=20,
        traits='Blast 6',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Frag Grenade',
        size=WeaponSize.Small,
        skill=traveller.AthleticsSkillDefinition,
        specialty=traveller.AthleticsSkillSpecialities.Dexterity,
        techLevel=6,
        cost=30,
        range=20,
        damage='5D',
        traits='Blast 9',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Incendiary Grenade',
        size=WeaponSize.Small,
        skill=traveller.AthleticsSkillDefinition,
        specialty=traveller.AthleticsSkillSpecialities.Dexterity,
        techLevel={
            StockWeaponSet.CSC2: 8,
            StockWeaponSet.CSC2023: 7},
        cost=75,
        range=20,
        damage='2D',
        traits='Blast 3, Fire',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Neurotoxin Grenade',
        size=WeaponSize.Small,
        skill=traveller.AthleticsSkillDefinition,
        specialty=traveller.AthleticsSkillSpecialities.Dexterity,
        techLevel=9,
        cost=250,
        range=20,
        damage='Special',
        traits='Blast 9',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Plasma Grenade',
        size=WeaponSize.Small,
        skill=traveller.AthleticsSkillDefinition,
        specialty=traveller.AthleticsSkillSpecialities.Dexterity,
        techLevel=16,
        cost=500,
        range=20,
        damage='8D',
        traits='Blast 6',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Smoke Grenade',
        size=WeaponSize.Small,
        skill=traveller.AthleticsSkillDefinition,
        specialty=traveller.AthleticsSkillSpecialities.Dexterity,
        techLevel=6,
        cost=15,
        range=20,
        traits='Blast 9',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Stun Grenade',
        size=WeaponSize.Small,
        skill=traveller.AthleticsSkillDefinition,
        specialty=traveller.AthleticsSkillSpecialities.Dexterity,
        techLevel=7,
        cost=30,
        range=20,
        damage='3D',
        traits='Blast 9, Stun',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Thermal Smoke Grenade',
        size=WeaponSize.Small,
        skill=traveller.AthleticsSkillDefinition,
        specialty=traveller.AthleticsSkillSpecialities.Dexterity,
        techLevel=7,
        cost=30,
        range=20,
        traits='Blast 9',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Tranq Gas Grenade',
        size=WeaponSize.Small,
        skill=traveller.AthleticsSkillDefinition,
        specialty=traveller.AthleticsSkillSpecialities.Dexterity,
        techLevel=8,
        cost=75,
        range=20,
        damage='Special',
        traits='Blast 9',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Breaching Charge',
        size=WeaponSize.Small,
        skill=traveller.ExplosivesSkillDefinition,
        techLevel=8,
        cost=250,
        damage='4D',
        traits='AP 6, Blast 1',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Complex Chemical Charge',
        size=WeaponSize.Small,
        skill=traveller.ExplosivesSkillDefinition,
        techLevel=10,
        cost=500,
        damage='4D',
        traits='AP 15, Blast 9',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Fusion Block',
        size=WeaponSize.Small,
        skill=traveller.ExplosivesSkillDefinition,
        techLevel=16,
        cost=10000,
        damage='1DD',
        traits={
            StockWeaponSet.CSC2: 'Blast 12, Radiation',
            StockWeaponSet.CSC2023: 'AP 50, Blast 12, Radiation'},
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Neutrino Detonator',
        size=WeaponSize.Small,
        skill=traveller.ExplosivesSkillDefinition,
        techLevel=17,
        cost=50000,
        damage='8D',
        traits={
            StockWeaponSet.CSC2: 'Blast 25',
            StockWeaponSet.CSC2023: 'AP ∞, Blast 25'},
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Plastic Explosive',
        size=WeaponSize.Small,
        skill=traveller.ExplosivesSkillDefinition,
        techLevel=6,
        cost=200,
        damage='3D',
        traits='Blast 9',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Pocket Nuke',
        size=WeaponSize.Small,
        skill=traveller.ExplosivesSkillDefinition,
        techLevel=12,
        cost=250000,
        damage='6DD',
        traits='Blast 1,000, Radiation',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='TDX',
        size=WeaponSize.Small,
        skill=traveller.ExplosivesSkillDefinition,
        techLevel=12,
        cost=1000,
        damage='4D',
        traits='Blast 15',
        compatible=_AllCompatible),
    # NOTE: The Atlatl isn't a weapon it's a tool that allows you to throw
    # darts or javelin better. It doubles the range and allows you to add
    # your DEX _AND_ STR bonus to the damage.
    _StockWeaponDescription(
        name='Atlatl - Dart',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Archaic,
        techLevel=0,
        cost=30,
        range=50,
        magazineSize=1,
        magazineCost=20,
        damage='2D-2 + STR & DEX bonus',
        traits='One Use, Silent',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Atlatl - Javelin',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Archaic,
        techLevel={
            StockWeaponSet.CSC2: 1,
            StockWeaponSet.CSC2023: 0},
        cost={
            StockWeaponSet.CSC2: 35,
            StockWeaponSet.CSC2023: 30},
        range=25,
        magazineSize=1,
        magazineCost=10,
        damage='2D + STR & DEX bonus',
        traits={
            StockWeaponSet.CSC2: 'One Use',
            StockWeaponSet.CSC2023: 'One Use, Silent'},
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Compound Cam Bow',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Archaic,
        techLevel=5,
        cost=250,
        range=100,
        magazineSize=1,
        magazineCost=5,
        multiLink=True,
        damage='3D-3',
        traits={
            StockWeaponSet.CSC2: 'AP 2',
            StockWeaponSet.CSC2023: 'AP 2, Silent'},
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Crossbow',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Archaic,
        techLevel={
            StockWeaponSet.CSC2: 2,
            StockWeaponSet.CSC2023: 1},
        cost=200,
        magazineSize=1,
        magazineCost={
            StockWeaponSet.CSC2: 5,
            StockWeaponSet.CSC2023: 1},
        multiLink=True,
        damage='3D-3',
        traits={
            StockWeaponSet.CSC2: 'AP 2',
            StockWeaponSet.CSC2023: 'AP 2, Silent'},
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Dart',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Archaic,
        techLevel=0,
        cost=10,
        range=50,
        damage='2D-2',
        traits='One Use, Silent',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Javelin',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Archaic,
        techLevel={
            StockWeaponSet.CSC2: 1,
            StockWeaponSet.CSC2023: 0},
        cost={
            StockWeaponSet.CSC2: 15,
            StockWeaponSet.CSC2023: 10},
        range=25,
        damage='2D',
        traits={
            StockWeaponSet.CSC2: 'One Use',
            StockWeaponSet.CSC2023: 'One Use, Silent'},
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Long Bow',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Archaic,
        techLevel={
            StockWeaponSet.CSC2: 2,
            StockWeaponSet.CSC2023: 1},
        cost=150,
        range=100,
        magazineSize=1,
        magazineCost={
            StockWeaponSet.CSC2: 5,
            StockWeaponSet.CSC2023: 1},
        multiLink=True,
        damage='3D-3',
        traits={
            StockWeaponSet.CSC2: 'AP 2, Bulky, Silent',
            StockWeaponSet.CSC2023: 'AP 2, Silent'},
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Repeating Crossbow',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Archaic,
        techLevel={
            StockWeaponSet.CSC2: 3,
            StockWeaponSet.CSC2023: 2},        
        cost=400,
        range=75,
        magazineSize=6,
        magazineCost={
            StockWeaponSet.CSC2: 30,
            StockWeaponSet.CSC2023: 6},
        multiLink=True,
        damage='2D',
        traits={
            StockWeaponSet.CSC2: '',
            StockWeaponSet.CSC2023: 'Silent'},
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Short Bow',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Archaic,
        techLevel={
            StockWeaponSet.CSC2: 1,
            StockWeaponSet.CSC2023: 0},             
        cost=50,
        range=75,
        magazineSize=1,
        magazineCost={
            StockWeaponSet.CSC2: 5,
            StockWeaponSet.CSC2023: 1},
        multiLink=True,
        damage='2D-3',
        traits={
            StockWeaponSet.CSC2: '',
            StockWeaponSet.CSC2023: 'Silent'},
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Cartridge Laser Carbine - TL 10',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=10,
        cost=2500,
        range=150,
        magazineSize=15,
        magazineCost=70,
        multiLink=True,
        damage='4D',
        traits='Zero-G',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Cartridge Laser Carbine - TL 12',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=12,
        cost=4000,
        range=200,
        magazineSize=20,
        magazineCost=70,
        multiLink=True,
        damage='4D+3',
        traits='Zero-G',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Cartridge Laser Rifle - TL 10',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=10,
        cost=3500,
        range=200,
        magazineSize=20,
        magazineCost=150,
        multiLink=True,
        damage='5D',
        traits='Auto 3, Zero-G',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Cartridge Laser Rifle - TL 12',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=12,
        cost=8000,
        range=400,
        magazineSize=25,
        magazineCost=150,
        multiLink=True,
        damage='5D+3',
        traits='Auto 3, Zero-G',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Cryo Rifle',
        size=WeaponSize.Heavy,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=13,
        cost=6000,
        range=10,
        magazineSize=12,
        magazineCost=150,
        multiLink=True,
        damage='4D',
        traits='Blast 3',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Flame Rifle',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=9,
        cost=2500,
        range=10,
        magazineSize=10,
        magazineCost=50,
        multiLink=True,
        damage='4D',
        traits='Blast 3, Fire',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Gauntlet Laser',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=10,
        cost=2500,
        range=20,
        magazineSize=100,
        magazineCost=1100,
        multiLink=True,
        damage='3D',
        traits='Zero-G',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Hand Flamer',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=10,
        cost=1500,
        range=5,
        magazineSize=5,
        magazineCost=25,
        multiLink=True,
        damage='3D',
        traits='Blast 2, Fire',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Heavy Laser Rifle',
        size=WeaponSize.Heavy,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=12,
        cost=14000,
        range=1200,
        magazineSize=12,
        magazineCost=500,
        multiLink=True,
        damage='6D',
        traits='Scope, Zero-G',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Ion Rifle - TL 14',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=14,
        cost=16000,
        range=600,
        magazineSize=100,
        magazineCost=5000,
        multiLink=True,
        damage='Special',
        traits='Zero-G',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Ion Rifle - TL 15',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=15,
        cost=24000,
        range=800,
        magazineSize=100,
        magazineCost=8000,
        multiLink=True,
        damage='Special',
        traits='Zero-G',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Laser Carbine - TL 9',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=9,
        cost=2500,
        range=150,
        magazineSize=50,
        magazineCost=1000,
        multiLink=True,
        damage='4D',
        traits='Zero-G',
        compatible=_AllCompatible),        
    _StockWeaponDescription(
        name='Laser Carbine - TL 11',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=11,
        cost=4000,
        range=200,
        magazineSize=50,
        magazineCost=3000,
        multiLink=True,
        damage='4D+3',
        traits='Zero-G',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Laser Pistol - TL 9',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=9,
        cost=2000,
        range=20,
        magazineSize=100,
        magazineCost=1000,
        multiLink=True,
        damage='3D',
        traits='Zero-G',
        compatible=_AllCompatible),        
    _StockWeaponDescription(
        name='Laser Pistol - TL 11',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=11,
        cost=3000,
        range=30,
        magazineSize=100,
        magazineCost=3000,
        multiLink=True,
        damage='3D+3',
        traits='Zero-G',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Laser Rifle - TL 9',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=9,
        cost=3500,
        range=200,
        magazineSize=100,
        magazineCost=1500,
        multiLink=True,
        damage='5D',
        traits='Zero-G',
        compatible=_AllCompatible),        
    _StockWeaponDescription(
        name='Laser Rifle - TL 11',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=11,
        cost=8000,
        range=400,
        magazineSize=100,
        magazineCost=3500,
        multiLink=True,
        damage='5D+3',
        traits='Zero-G',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Laser Sniper Rifle',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=12,
        cost=9000,
        range=600,
        magazineSize=6,
        magazineCost=250,
        multiLink=True,
        damage={
            StockWeaponSet.Core2: '5D+3',
            StockWeaponSet.Core2022: '5D+3',
            StockWeaponSet.CSC2: '6D+3',
            StockWeaponSet.CSC2023: '5D+3'},
        traits='Scope, Zero-G',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Maser Pistol',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=17,
        cost=25000,
        range=20,
        magazineSize=12,
        multiLink=True,
        damage='3D+3',
        traits='AP 10, Zero-G',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Maser Rifle',
        size=WeaponSize.Heavy,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=16,
        cost=30000,
        range=300,
        magazineSize=20,
        multiLink=True,
        damage='5D+3',
        traits='AP 10, Zero-G',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Matter Disintegrator - TL 18',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=18,
        cost=2500000,
        range=5,
        magazineCost=50000,
        multiLink=True,
        damage='1DD',
        traits='Zero-G',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Matter Disintegrator - TL 19',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=19,
        cost=4000000,
        range=10,
        multiLink=True,
        damage='2DD',
        traits='Zero-G',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Pepper Spray',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=5,
        cost=5,
        range=3,
        magazineSize=5,
        magazineCost=5,
        damage='Special',
        traits='Stun',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Personal Defence Laser',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=13,
        cost=6000,
        range=25,
        magazineSize=25,
        magazineCost=100,
        multiLink=True,
        damage='3D+3',
        traits='Auto 2, Zero-G',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Plasma Rifle',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=16,
        cost=100000,
        range=300,
        multiLink=True,
        damage={
            StockWeaponSet.Core2: '6D',
            StockWeaponSet.Core2022: '6D',
            StockWeaponSet.CSC2: '1DD',
            StockWeaponSet.CSC2023: '6D'},
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Solar Beam Rifle',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=17,
        cost=200000,
        range=500,
        magazineSize=20,
        multiLink=True,
        damage='1DD',
        traits='AP 20, Zero-G',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Stagger Laser Rifle - TL 12',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=12,
        cost=10000,
        range=300,
        magazineSize=50,
        magazineCost=5000,
        multiLink=True,
        damage='5D',
        traits='Auto 2, Zero-G',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Stagger Laser Rifle - TL 14',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=14,
        cost=15000,
        range=350,
        magazineSize=100,
        magazineCost=6000,
        multiLink=True,
        damage='5D+3',
        traits='Auto 3, Zero-G',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Stun Blaster',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=13,
        cost=3000,
        range=20,
        magazineSize=200,
        magazineCost=500,
        multiLink=True,
        damage='4D',
        traits='Stun, Zero-G',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Stun Carbine',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=12,
        cost=2000,
        range=20,
        magazineSize=50,
        magazineCost=200,
        multiLink=True,
        damage='3D',
        traits='Stun, Zero-G',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Stunner - TL 8',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=8,
        cost=500,
        range=5,
        magazineSize=100,
        magazineCost=200,
        multiLink=True,
        damage='2D',
        traits='Stun, Zero-G',
        compatible=_AllCompatible),        
    _StockWeaponDescription(
        name='Stunner - TL 10',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=10,
        cost=750,
        range=5,
        magazineSize=100,
        magazineCost=200,
        multiLink=True,
        damage='2D+3',
        traits='Stun, Zero-G',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Stunner - TL 12',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        techLevel=12,
        cost=1000,
        range=10,
        magazineSize=100,
        magazineCost=200,
        multiLink=True,
        damage='3D',
        traits='Stun, Zero-G',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Accelerator Rifle - TL 9',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=9,
        cost=900,
        # NOTE: The original CSC has 25 but I suspect that is a misprint
        # as the Core 2e, Core 2022 & CSC 2023 all have it as 250
        range=250,
        magazineSize=15,
        magazineCost=30,
        multiLink=True,
        damage='3D',
        traits='Zero-G',
        compatible=_AllCompatible),        
    _StockWeaponDescription(
        name='Accelerator Rifle - TL 11',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=11,
        cost=1500,
        range=400,
        magazineSize=20,
        magazineCost=40,
        multiLink=True,
        damage='3D',
        traits='Zero-G',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Advanced Combat Rifle',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=10,
        cost=1000,
        range=450,
        magazineSize=40,
        magazineCost=15,
        multiLink=True,
        damage='3D',
        traits='Auto 3, Scope',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Air Rifle - TL 3',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=3,
        cost=225,
        range=50,
        magazineSize=1,
        magazineCost=1,
        multiLink=True,
        damage='2D',
        traits='Silent',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Air Rifle - TL 4',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=4,
        cost=350,
        range=75,
        magazineSize=1,
        magazineCost=1,
        multiLink=True,
        damage='3D-2',
        traits='Silent',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Antique Pistol',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel={
            StockWeaponSet.Core2: 3,
            StockWeaponSet.Core2022: 2,
            StockWeaponSet.CSC2: 3,
            StockWeaponSet.CSC2023: 2},
        cost=100,
        range=5,
        magazineSize=1,
        magazineCost=5,
        multiLink=True,
        damage='2D-3',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Antique Rifle',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel={
            StockWeaponSet.Core2: 3,
            StockWeaponSet.Core2022: 2,
            StockWeaponSet.CSC2: 3,
            StockWeaponSet.CSC2023: 2},
        cost=150,
        range=25,
        magazineSize=1,
        magazineCost=10,
        multiLink=True,
        damage='3D-3',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Assault Pistol',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=6,
        cost=250,
        range=10,
        magazineSize=15,
        magazineCost=10,
        multiLink=True,
        damage='3D-3',
        traits='Auto 2',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Assault Rifle',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=7,
        cost=500,
        range=200,
        magazineSize=30,
        magazineCost=15,
        multiLink=True,
        damage='3D',
        traits='Auto 2',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Assault Shotgun',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=6,
        cost=500,
        range=50,
        magazineSize=24,
        magazineCost=40,
        multiLink=True,
        damage='4D',
        traits='Auto 2, Bulky',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Autopistol',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel={
            StockWeaponSet.Core2: 6,
            StockWeaponSet.Core2022: 5,
            StockWeaponSet.CSC2: 6,
            StockWeaponSet.CSC2023: 5},
        cost=200,
        range=10,
        magazineSize=15,
        magazineCost=10,
        multiLink=True,
        damage='3D-3',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Autorifle',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=6,
        cost=750,
        range=300,
        magazineSize=20,
        magazineCost=10,
        multiLink=True,
        damage='3D',
        traits='Auto 2',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Big Game Rifle',
        size=WeaponSize.Heavy,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=5,
        cost=1250,
        range=200,
        magazineSize=5,
        magazineCost=50,
        multiLink=True,
        damage='3D+3',
        traits='Very Bulky',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Body Pistol',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=8,
        cost=500,
        range=5,
        magazineSize=6,
        magazineCost=10,
        multiLink=True,
        damage='2D',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Cartridge Pistol',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=7,
        cost=300,
        range=20,
        magazineSize=6,
        magazineCost=10,
        multiLink=True,
        damage='4D',
        traits='Bulky',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Coach Pistol',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=3,
        cost=200,
        range=5,
        magazineSize=2,
        magazineCost=10,
        multiLink=True,
        damage='4D-3',
        traits='Dangerous',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Duck\'s Foot Pistol',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=3,
        cost=300,
        range=5,
        magazineSize=24,
        magazineCost=25,
        multiLink=True,
        damage='3D-3',
        traits='Auto 4, Dangerous',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Flechette Pistol',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=9,
        cost=275,
        range=10,
        magazineSize=20,
        magazineCost=10,
        multiLink=True,
        damage='3D-2',
        traits='Silent',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Flechette Submachine Gun',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=9,
        cost=500,
        range=20,
        magazineSize=40,
        magazineCost=20,
        multiLink=True,
        damage='3D-2',
        traits='Auto 3, Silent',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Gauss Assault Gun',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=12,
        cost=1300,
        range=20,
        magazineSize=36,
        magazineCost=35,
        multiLink=True,
        damage='4D',
        traits='AP 5, Auto 2',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Gauss Pistol',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=13,
        cost=500,
        range=20,
        magazineSize=40,
        magazineCost=20,
        multiLink=True,
        damage='3D',
        traits='AP 3, Auto 2',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Gauss Rifle',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=12,
        cost=1500,
        range=600,
        magazineSize=80,
        magazineCost={
            StockWeaponSet.Core2: 40,
            StockWeaponSet.Core2022: 40,
            StockWeaponSet.CSC2: 40,
            StockWeaponSet.CSC2023: 80},
        multiLink=True,
        damage='4D',
        traits='AP 5, Auto 3, Scope',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Gauss Sniper RIfle',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=12,
        cost=2500,
        range=1000,
        magazineSize=12,
        magazineCost=20,
        multiLink=True,
        damage='5D',
        traits='AP 6, Scope',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Gauss Submachine Gun',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=12,
        cost=1000,
        range=50,
        magazineSize=60,
        magazineCost=60,
        multiLink=True,
        damage='3D+2',
        traits='AP 3, Auto 4',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Heavy Advanced Combat Rifle',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=10,
        cost=2000,
        range=450,
        magazineSize=30,
        magazineCost=20,
        multiLink=True,
        damage='4D',
        traits='Auto 2, Bulky, Scope',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Heavy Revolver',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel={
            StockWeaponSet.CSC2: 6,
            StockWeaponSet.CSC2023: 5},
        cost=400,
        range=10,
        magazineSize=6,
        magazineCost=15,
        multiLink=True,
        damage='4D-3',
        traits='Bulky',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Light Shotgun',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=4,
        cost=150,
        range=40,
        magazineSize=6,
        magazineCost=10,
        multiLink=True,
        damage='3D',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Magrail Pistol',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=14,
        cost=750,
        range=15,
        magazineSize=20,
        magazineCost=60,
        multiLink=True,
        damage='3D+3',
        traits='Auto 4',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Magrail Rifle',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=14,
        cost=2500,
        range=150,
        magazineSize=30,
        magazineCost=100,
        multiLink=True,
        damage='4D+3',
        traits='Auto 6',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Revolver',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel={
            StockWeaponSet.Core2: 5,
            StockWeaponSet.Core2022: 4,
            StockWeaponSet.CSC2: 5,
            StockWeaponSet.CSC2023: 4},
        cost=150,
        range=10,
        magazineSize=6,
        magazineCost=5,
        multiLink=True,
        damage='3D-3',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Rifle',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=5,
        cost=200,
        range=250,
        magazineSize=5,
        magazineCost=10,
        multiLink=True,
        damage='3D',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Sawed-Off Shotgun',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel={
            StockWeaponSet.CSC2: 5,
            StockWeaponSet.CSC2023: 4},
        cost=200,
        range=10,
        magazineSize=1,
        magazineCost={
            StockWeaponSet.CSC2: 5,
            StockWeaponSet.CSC2023: 10},
        multiLink=True,
        damage='4D',
        traits='Bulky',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Shot Pistol',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=5,
        cost=60,
        range=2,
        magazineSize=1,
        magazineCost=5,
        multiLink=True,
        damage='3D',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Shotgun',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=4,
        cost=200,
        range=50,
        magazineSize=6,
        magazineCost=10,
        multiLink=True,
        damage='4D',
        traits='Bulky',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Sniper Rifle',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=8,
        cost=700,
        range=500,
        magazineSize=4,
        magazineCost=10,
        multiLink=True,
        damage='3D',
        traits='AP 5, Scope, Silent',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Snub Carbine',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=11,
        cost=500,
        range=75,
        magazineSize=20,
        magazineCost=30,
        multiLink=True,
        damage='3D-3',
        traits='Zero-G',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Snub Pistol',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=8,
        cost=150,
        range=5,
        magazineSize=6,
        magazineCost=10,
        multiLink=True,
        damage='3D-3',
        traits='Zero-G',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Spear Gun',
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=6,
        cost=50,
        range=25,
        magazineSize=1,
        magazineCost=10,
        multiLink=True,
        damage='3D',
        traits='Silent',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Submachine Gun',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=6,
        cost=400,
        range=25,
        magazineSize=20,
        magazineCost=10,
        multiLink=True,
        damage='3D',
        traits='Auto 3',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Universal Autopistol',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=8,
        cost=300,
        range=10,
        magazineSize=10,
        magazineCost=10,
        multiLink=True,
        damage='3D-3',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Zip Gun',
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        techLevel=3,
        cost=50,
        range=5,
        magazineSize=1,
        magazineCost=5,
        multiLink=True,
        damage='2D-3',
        traits='Dangerous',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Infantry Mortar',
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Artillery,
        techLevel=5,
        cost=3500,
        range=1,
        magazineSize=1,
        magazineCost=50,
        multiLink=True,
        damage='5D',
        traits='Artillery, Blast 5',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Support Mortar',
        size=WeaponSize.Vehicle,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Artillery,
        techLevel=7,
        cost=11000,
        range=3,
        magazineSize=1,
        magazineCost=100,
        multiLink=True,
        damage='9D',
        traits='Artillery, Blast 6',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Anti-Material Rifle',
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel=7,
        cost=3000,
        range=1000,
        magazineSize=1,
        magazineCost={
            StockWeaponSet.CSC2: 100,
            StockWeaponSet.CSC2023: 10},
        multiLink=True,
        damage='5D',
        traits='AP 5, Scope, Very Bulky',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='ARL - PDW',
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel=10,
        cost=200,
        range=50,
        magazineSize=20,
        magazineCost=100,
        multiLink=True,
        damage='4D',
        traits='Auto 4, Zero-G',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='ARL - Standard',
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel=10,
        cost=800,
        range=80,
        magazineSize=20,
        magazineCost=100,
        multiLink=True,
        damage='4D',
        traits='Zero-G',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='ARL - Support',
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel=10,
        cost=1300,
        range=80,
        magazineSize=40,
        magazineCost=200,
        multiLink=True,
        damage='4D',
        traits='Auto 4, Zero-G',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='CPPG-11',
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel=11,
        cost=8000,
        range=200,
        magazineSize=6,
        magazineCost=300,
        multiLink=True,
        damage='6D',
        traits='AP 6, Blast 2, Bulky, Scope',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='CPPG-12',
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel=12,
        cost=15000,
        range=300,
        magazineSize=6,
        magazineCost=450,
        multiLink=True,
        damage='8D',
        traits='AP 8, Blast 3, Bulky, Scope',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='CPPG-13',
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel=13,
        cost=25000,
        range=500,
        magazineSize=6,
        magazineCost=600,
        multiLink=True,
        damage='1DD',
        traits='AP 10, Blast 3, Bulky, Scope',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Cryojet',
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel=11,
        cost=4000,
        range=10,
        magazineSize=16,
        magazineCost=200,
        multiLink=True,
        damage='4D',
        traits='Blast 5, Bulky',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Disposable Plasma Launcher',
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel=12,
        cost=8000,
        range=300,
        damage='2DD',
        traits='One Use, Smart',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Early Machinegun',
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel=4,
        cost=1200,
        range=400,
        magazineSize=30,
        magazineCost=100,
        multiLink=True,
        damage='3D',
        traits='Auto 3, Very Bulky',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='FGHP-14', # NOTE: FGMP in Core 2e rules
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel=14,
        cost=100000,
        range=450,
        multiLink=True,
        damage='2DD',
        traits='Radiation, Very Bulky',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='FGHP-15', # NOTE: FGMP in Core 2e rules
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel=15,
        cost=400000,
        range=450,
        multiLink=True,
        damage='2DD',
        traits='Bulky, Radiation',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='FGHP-16', # NOTE: FGMP in Core 2e rules
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel=16,
        cost=500000,
        range=450,
        multiLink=True,
        damage='2DD',
        traits='Radiation',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Flamethrower - TL 4',
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel=4,
        cost=800,
        range=5,
        magazineSize=30,
        magazineCost=60,
        multiLink=True,
        damage='3D',
        traits='Blast 5, Bulky, Fire',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Flamethrower - TL 6',
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel=6,
        cost=1500,
        range=5,
        magazineSize=40,
        magazineCost=80,
        multiLink=True,
        damage='4D',
        traits='Blast 5, Bulky, Fire',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Flamethrower - TL 8',
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel=8,
        cost=2000,
        range=10,
        magazineSize=50,
        magazineCost=100,
        multiLink=True,
        damage='4D',
        traits='Blast 5, Fire',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Grenade Launcher',
        size=WeaponSize.Medium,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel=7,
        cost=400,
        range=100,
        magazineSize=6,
        damage='As grenade',
        traits={
            StockWeaponSet.Core2: 'Bulky',
            StockWeaponSet.Core2022: 'Bulky',
            StockWeaponSet.CSC2: 'Bulky',
            StockWeaponSet.CSC2023: ''},
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Light Assault Gun',
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel=8,
        cost=4000,
        range=800,
        magazineSize=5,
        magazineCost=100,
        multiLink=True,
        damage='7D',
        traits='AP 5, Very Bulky',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Light Gatling Laser',
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel=9,
        cost=4500,
        range=180,
        magazineSize=100,
        magazineCost=300,
        multiLink=True,
        damage='3D',
        traits='Auto 4, Zero-G',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Machinegun',
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel={
            StockWeaponSet.Core2: 6,
            StockWeaponSet.Core2022: 6,
            StockWeaponSet.CSC2: 6,
            StockWeaponSet.CSC2023: 5},
        cost=1500,
        range=500,
        magazineSize=60,
        magazineCost=100,
        multiLink=True,
        damage='3D',
        traits={
            StockWeaponSet.Core2: 'Auto 4',
            StockWeaponSet.Core2022: 'Auto 4',
            StockWeaponSet.CSC2: 'Auto 4',
            StockWeaponSet.CSC2023: 'Auto 4, Bulky'},
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='PGHP-12', # NOTE: PGMP in Core 2e rules
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel=12,
        cost=20000,
        range=250,
        multiLink=True,
        damage='1DD',
        traits='Very Bulky',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='PGHP-13', # NOTE: PGMP in Core 2e rules
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel=13,
        cost=65000,
        range=450,
        multiLink=True,
        damage='1DD',
        traits='Bulky',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='PGHP-14', # NOTE: PGMP in Core 2e rules
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel=14,
        cost=100000,
        range=450,
        multiLink=True,
        damage='1DD',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Plasma Jet - TL 12',
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel=12,
        cost=16000,
        range=25,
        multiLink=True,
        damage='1DD',
        traits='Blast 5, Very Bulky',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Plasma Jet - TL 14',
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel=14,
        cost=80000,
        range=50,
        multiLink=True,
        damage='1DD',
        traits='Blast 10, Bulky',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='RAM Grenade Launcher',
        size=WeaponSize.Medium,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel=8,
        cost=800,
        range=250,
        magazineSize=6,
        damage='As Grenade',
        traits='Auto 3, Bulky',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Rapid-Fire Machinegun',
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel=7,
        cost=3000,
        range=500,
        magazineSize=60,
        magazineCost=100,
        multiLink=True,
        damage='3D',
        traits='Auto 4 (8)',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Rocket Launcher - TL 6',
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel=6,
        cost=2000,
        range=120,
        magazineSize=1,
        magazineCost=300,
        damage='4D',
        traits='Blast 6',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Rocket Launcher - TL 7',
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel=7,
        cost=2000,
        range=150,
        magazineSize=1,
        magazineCost=400,
        damage='4D+3',
        traits='Blast 6, Smart',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Rocket Launcher - TL 8',
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel=8,
        cost=2000,
        range=200,
        magazineSize=2,
        magazineCost=600,
        damage='5D',
        traits='Blast 6, Scope, Smart',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Rocket Launcher - TL 9',
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        techLevel=9,
        cost=2000,
        range=250,
        magazineSize=2,
        magazineCost=800,
        damage='5D+6',
        traits='Blast 6, Scope, Smart',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Light Cannon',
        size=WeaponSize.Vehicle,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Vehicle,
        techLevel=5,
        cost=200000,
        range=1.5,
        magazineSize=50,
        magazineCost=5000,
        multiLink=True,
        damage='6D',
        traits='Blast 6',
        compatible=[StockWeaponSet.CSC2023]),        
    _StockWeaponDescription(
        name='Medium Cannon', # NOTE: This is Cannon in Core rules and CSC 2
        size=WeaponSize.Vehicle,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Vehicle,
        techLevel=8,
        cost=400000,
        range=2,
        magazineSize=30,
        magazineCost=5000,
        multiLink=True,
        damage={
            StockWeaponSet.Core2: '8D',
            StockWeaponSet.Core2022: '8D',
            StockWeaponSet.CSC2: '1DD',
            StockWeaponSet.CSC2023: '1DD'},
        traits='Blast 10',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Heavy Cannon',
        size=WeaponSize.Vehicle,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Vehicle,
        techLevel={
            StockWeaponSet.CSC2: 8,
            StockWeaponSet.CSC2023: 7},
        cost=600000,
        range=3,
        magazineSize=10,
        magazineCost=5000,
        multiLink=True,
        damage='2DD',
        traits='Blast 10',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Fusion Gun - TL 13',
        size=WeaponSize.Vehicle,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Vehicle,
        techLevel=13,
        cost=2000000,
        range=3,
        multiLink=True,
        damage='3DD',
        traits='AP 10, Blast 25, Radiation',
        compatible=[StockWeaponSet.CSC2, StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Fusion Gun - TL 14', # NOTE: This is Fusion Cannon in Core 2e rules
        size=WeaponSize.Vehicle,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Vehicle,
        techLevel=14,
        cost=3000000,
        range=5,
        multiLink=True,
        damage='3DD',
        traits='AP 20, Blast 20, Radiation',
        compatible=[StockWeaponSet.Core2, StockWeaponSet.CSC2, StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Fusion Gun - TL 15',
        size=WeaponSize.Vehicle,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Vehicle,
        techLevel=13,
        cost=8000000,
        range=10,
        multiLink=True,
        damage='3DD',
        traits='AP 30, Blast 30, Radiation',
        compatible=[StockWeaponSet.CSC2, StockWeaponSet.CSC2023]),        
    _StockWeaponDescription(
        name='Heavy Machinegun',
        size=WeaponSize.Vehicle,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Vehicle,
        techLevel=6,
        cost=4500,
        range=1,
        magazineSize=100,
        magazineCost=400,
        multiLink=True,
        damage={
            StockWeaponSet.Core2: '4D',
            StockWeaponSet.Core2022: '4D',
            StockWeaponSet.CSC2: '4D',
            StockWeaponSet.CSC2023: '5D'},
        traits='Auto 3',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Light Laser Cannon',
        size=WeaponSize.Vehicle,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Vehicle,
        techLevel=9,
        cost=60000,
        range=2,
        multiLink=True,
        damage='8D',
        traits='AP 5',
        compatible=[StockWeaponSet.CSC2023]),        
    _StockWeaponDescription(
        name='Medium Laser Cannon', # NOTE: This is Laser Cannon in Core and CSC 2e rules
        size=WeaponSize.Vehicle,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Vehicle,
        techLevel=9,
        cost=100000,
        range=2.5,
        multiLink=True,
        damage={
            StockWeaponSet.Core2: '4D',
            StockWeaponSet.Core2022: '1DD',
            StockWeaponSet.CSC2: '1DD',
            StockWeaponSet.CSC2023: '1DD'},
        traits='AP 10',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Heavy Laser Cannon',
        size=WeaponSize.Vehicle,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Vehicle,
        techLevel=9,
        cost=250000,
        range=25,
        multiLink=True,
        damage={
            StockWeaponSet.CSC2: '2DD',
            StockWeaponSet.CSC2023: '1DD'},
        traits='AP 20',
        compatible=_SupplyCatalogueCompatible),           
    _StockWeaponDescription(
        name='Light Anti-Air Missile',
        size=WeaponSize.Vehicle,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Vehicle,
        techLevel=7,
        cost=5000,
        range=5,
        magazineSize=1,
        damage='6D',
        traits='One Use, Smart',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Light Autocannon',
        size=WeaponSize.Vehicle,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Vehicle,
        techLevel=6,
        cost=10000,
        range=1,
        magazineSize=500,
        magazineCost=1000,
        multiLink=True,
        # NOTE: The Core 2e rules have this as 1D (p136) but I think
        # that must be a miss-print as all other books have it as 6D
        damage='6D',
        traits='Auto 3',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Rocket Pod',
        size=WeaponSize.Vehicle,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Vehicle,
        techLevel=6,
        cost=8000,
        range=1.5,
        magazineSize=18,
        magazineCost=8000,
        damage='4D',
        traits='Auto 3, Blast 5',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Tac Launcher - Anti-Aircraft',
        size=WeaponSize.Vehicle,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Vehicle,
        techLevel=10,
        cost=16000,
        range=10,
        magazineSize=4,
        magazineCost=8000,
        damage='8D',
        traits={
            StockWeaponSet.CSC2: 'Scope, Smart, Track',
            StockWeaponSet.CSC2023: 'Scope, Smart'},
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Tac Launcher - Anti-Personnel',
        size=WeaponSize.Vehicle,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Vehicle,
        techLevel=10,
        cost=12000,
        range=6,
        magazineSize=4,
        magazineCost=4000,
        damage='4D',
        traits='Blast 10, Scope, Smart',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Tac Launcher - Armour Piercing',
        size=WeaponSize.Vehicle,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Vehicle,
        techLevel=10,
        cost=15000,
        range=6,
        magazineSize=4,
        magazineCost=6000,
        damage='8D',
        traits='AP 10, Scope, Smart',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='VRF Gauss Gun',
        size=WeaponSize.Vehicle,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Vehicle,
        techLevel=12,
        cost=20000,
        range=0.75,
        magazineSize=400,
        magazineCost=1000,
        multiLink=True,
        damage='4D',
        traits='AP 5, Auto 8',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='VRF Machinegun',
        size=WeaponSize.Vehicle,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Vehicle,
        techLevel=7,
        cost=12000,
        range=0.5,
        magazineSize=400,
        magazineCost=1250,
        multiLink=True,
        damage='4D',
        traits='Auto 6',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Arc-Field Weapon',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        techLevel=14,
        cost=25000,
        damage='5D+2',
        traits='AP 30',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Assault Pike - TL 5',
        techLevel=5,
        cost=200,
        size=WeaponSize.Heavy,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        damage='4D',
        traits='AP 4, One Use',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Assault Pike - TL 8',
        size=WeaponSize.Medium,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        techLevel=8,
        cost=400,
        damage='4D',
        traits='AP 4, One Use',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Battle Axe',
        size=WeaponSize.Medium,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        techLevel={
            StockWeaponSet.CSC2: 2,
            StockWeaponSet.CSC2023: 1},
        cost=225,
        damage='3D',
        traits='AP 2, Bulky',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Blade',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        techLevel={
            StockWeaponSet.Core2: 2,
            StockWeaponSet.Core2022: 2,
            StockWeaponSet.CSC2: 2,
            StockWeaponSet.CSC2023: 1},
        cost=100,
        damage='2D',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Broadsword',
        size=WeaponSize.Medium,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        techLevel={
            StockWeaponSet.Core2: 2,
            StockWeaponSet.Core2022: 2,            
            StockWeaponSet.CSC2: 2,
            StockWeaponSet.CSC2023: 1},
        cost=500,
        damage='4D',
        traits='Bulky',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Chaindrive Axe',
        size=WeaponSize.Medium,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        techLevel=10,
        cost=600,
        damage='4D',
        traits='AP 4, Bulky',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Chaindrive Sword',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        techLevel=10,
        cost=500,
        damage='4D',
        traits='AP 2',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Cutlass',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        techLevel=2,
        cost=200,
        damage='3D',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Dagger',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        techLevel=1,
        cost=10,
        damage='1D+2',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Great Axe',
        size=WeaponSize.Heavy,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        techLevel=1,
        cost=750,
        damage='4D+2',
        traits='Smasher, Very Bulky',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Hatchet',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        techLevel={
            StockWeaponSet.CSC2: 3,
            StockWeaponSet.CSC2023: 1},
        cost=50,
        damage='2D+2',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Knife',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        techLevel=1,
        cost=5,
        damage='1D',
        compatible=[StockWeaponSet.CSC2]),    
    _StockWeaponDescription(
        name='Lance',
        size=WeaponSize.Medium,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        techLevel=1,
        cost={
            StockWeaponSet.CSC2: 75,
            StockWeaponSet.CSC2023: 250},
        damage='5D',
        traits='AP 4',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Long Blade - TL 1',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        techLevel=1,
        cost=200,
        damage='3D',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Long Blade - TL 2',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        techLevel=2,
        cost=200,
        damage='3D',
        compatible=[StockWeaponSet.CSC2]),        
    _StockWeaponDescription(
        name='Long Blade - TL 3',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        techLevel=3,
        cost=300,
        damage='3D+2',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Monoblade',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        techLevel=12,
        cost=2500,
        damage='3D',
        traits='AP 10',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Monofilament Axe',
        size=WeaponSize.Medium,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        techLevel=12,
        cost=3000,
        damage='4D',
        traits='AP 15, Bulky, Smasher',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Piston Spear',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        techLevel=7,
        cost=400,
        damage='3D+2',
        traits={
            StockWeaponSet.CSC2: '',
            StockWeaponSet.CSC2023: 'AP 2'},
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Psi Blade',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        techLevel=16,
        cost=30000,
        damage='2D',
        traits={
            StockWeaponSet.CSC2: '',
            StockWeaponSet.CSC2023: 'Special (PSI)'},
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Psi Dagger',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        techLevel={
            StockWeaponSet.CSC2: 17,
            StockWeaponSet.CSC2023: 16},
        cost=25000,
        damage='1D+2',
        traits={
            StockWeaponSet.CSC2: '',
            StockWeaponSet.CSC2023: 'Special (PSI)'},
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Rapier',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        techLevel={
            StockWeaponSet.Core2: 3,
            StockWeaponSet.Core2022: 3,
            StockWeaponSet.CSC2: 3,
            StockWeaponSet.CSC2023: 2},
        cost=200,
        damage='2D',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Spear',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        techLevel={
            StockWeaponSet.CSC2: 1,
            StockWeaponSet.CSC2023: 0},
        cost=10,
        damage='2D',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Static Axe - TL 11',
        size=WeaponSize.Heavy,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        techLevel=11,
        cost=750,
        damage='4D',
        traits='AP 6, Smasher',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Static Axe - TL 12',
        size=WeaponSize.Medium,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        techLevel=12,
        cost=1000,
        damage='4D+2',
        traits='AP 8, Smasher',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Static Blade - TL 11',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        techLevel=11,
        cost=700,
        damage='3D',
        traits='AP 5',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Static Blade - TL 12',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        techLevel=12,
        cost=900,
        damage='3D+2',
        traits='AP 6',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Stealth Dagger',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        techLevel=8,
        cost=175,
        damage='1D+2',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Stone Axe',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        techLevel=0,
        cost=5,
        damage={
            StockWeaponSet.CSC2: '2D',
            StockWeaponSet.CSC2023: '2D+1'},
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='War Pick',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        techLevel={
            StockWeaponSet.CSC2: 3,
            StockWeaponSet.CSC2023: 1},
        cost=275,
        damage='2D+2',
        traits='AP 4',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Anti-Armour Flail',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        techLevel=8,
        cost=250,
        damage='4D',
        traits='AP 5, One Use',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Boarding Shield',
        size=WeaponSize.Medium,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        techLevel=9,
        cost=1500,
        damage='1D',
        traits={
            StockWeaponSet.CSC2: '',
            StockWeaponSet.CSC2023: 'Bulky'},
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Buckler',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        techLevel={
            StockWeaponSet.CSC2: 2,
            StockWeaponSet.CSC2023: 1},
        cost=10,
        damage='1D',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Club',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        techLevel={
            StockWeaponSet.Core2: 1,
            StockWeaponSet.Core2022: 1,            
            StockWeaponSet.CSC2: 1,
            StockWeaponSet.CSC2023: 0},
        damage='2D',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Expandable Shield',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        techLevel=12,
        cost=2500,
        damage='1D',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Gravitic Shield',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        techLevel=17,
        cost=2500,
        damage='1D',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Gravity Hammer',
        size=WeaponSize.Medium,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        techLevel=13,
        cost=10000,
        damage='5D',
        traits='AP 50, Bulky, Smasher',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Large Shield',
        size=WeaponSize.Medium,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        techLevel=1,
        cost=200,
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Mace',
        size=WeaponSize.Medium,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        techLevel=1,
        cost=20,
        damage='2D+2',
        traits='Bulky, Smasher',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Riot Shield',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        techLevel=6,
        cost=175,
        damage='1D',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Sap',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        techLevel={
            StockWeaponSet.CSC2: 2,
            StockWeaponSet.CSC2023: 1},
        cost=30,
        damage='1D',
        traits='Stun',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Shield',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        techLevel={
            StockWeaponSet.Core2: 1,
            StockWeaponSet.Core2022: 1,            
            StockWeaponSet.CSC2: 1,
            StockWeaponSet.CSC2023: 0},
        cost=150,
        damage='1D',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Sledgehammer',
        size=WeaponSize.Heavy,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        techLevel=1,
        cost=30,
        damage='4D',
        traits='Smasher, Very Bulky',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Staff',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        techLevel=1,
        cost={
            StockWeaponSet.Core2: None,
            StockWeaponSet.Core2022: None,            
            StockWeaponSet.CSC2: None,
            StockWeaponSet.CSC2023: 5},
        damage='2D',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Static Maul',
        size=WeaponSize.Medium,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        techLevel=11,
        cost=650,
        damage='3D',
        traits='AP 4, Smasher',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Stunstick',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        techLevel=8,
        cost=300,
        damage='2D',
        traits='Stun',
        compatible=_AllCompatible),
    _StockWeaponDescription(
        name='Brass Knuckles',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Unarmed,
        techLevel=1,
        cost=10,
        damage='1D+2',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Claw - Arc-Field',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Unarmed,
        techLevel=14,
        cost=25000,
        damage='4D',
        traits='AP 30',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Claw - Edging',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Unarmed,
        techLevel=11,
        cost=3000,
        damage='2D+2',
        traits='AP 4',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Claw - Hardened',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Unarmed,
        techLevel=10,
        cost=1000,
        damage='1D+2',
        traits='AP 2',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Claw - Monofilament',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Unarmed,
        techLevel=12,
        cost=5000,
        damage='3D',
        traits='AP 10',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Garotte',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Unarmed,
        techLevel={
            StockWeaponSet.CSC2: 1,
            StockWeaponSet.CSC2023: 0},
        cost=10,
        damage='2D',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Handspikes',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Unarmed,
        techLevel=2,
        cost=100,
        damage='2D',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Knuckleblasters',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Unarmed,
        techLevel=8,
        cost=150,
        damage='5D',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Monofilament Garotte',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Unarmed,
        techLevel=12,
        cost=1000,
        damage='3D',
        traits='AP 10, Dangerous',
        compatible=[StockWeaponSet.CSC2023]),
    _StockWeaponDescription(
        name='Piston Fist',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Unarmed,
        techLevel=9,
        cost=150,
        damage='3D+2',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Stunfist',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Unarmed,
        techLevel=8,
        cost=250,
        damage='1D+2',
        traits='Stun',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Shock Whip',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Whip,
        techLevel=9,
        cost=450,
        damage='2D',
        traits='Stun',
        compatible=_SupplyCatalogueCompatible),
    _StockWeaponDescription(
        name='Whip',
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Whip,
        techLevel=1,
        cost=15,
        damage='D3',
        compatible=_SupplyCatalogueCompatible)
]

_WeaponDescriptionMap = {
    weaponSet: {desc.name(): desc.createStockWeapon(weaponSet) for desc in _WeaponDescriptions if desc.isCompatible(weaponSet)} \
    for weaponSet in StockWeaponSet}

def lookupStockWeapon(
        name: str,
        weaponSet: StockWeaponSet
        ) -> typing.Optional[StockWeapon]:
    weaponMap = _WeaponDescriptionMap.get(weaponSet)
    return weaponMap.get(name)

def findStockWeapons(
        weaponSet: StockWeaponSet,
        currentTL: typing.Optional[int]
        ) -> typing.Iterable[StockWeapon]:
    weaponMap = _WeaponDescriptionMap.get(weaponSet)
    if not weaponMap:
        return []
    if currentTL == None:
        return list(weaponMap.values())
    
    weapons = []
    for weapon in weaponMap.values():
        if weapon.techLevel() <= currentTL:
            weapons.append(weapon)
    return weapons