import enum
import traveller
import typing

class WeaponSize(enum.Enum):
    Small = 'Small'
    Medium = 'Medium'
    Heavy = 'Heavy'
    Vehicle = 'Vehicle'

class WeaponData(object):
    def __init__(
            self,
            name: str,
            techLevel: int,
            cost: int,
            size: WeaponSize,
            skill: traveller.SkillDefinition,
            specialty: typing.Optional[enum.Enum] = None,
            magazineCost: typing.Optional[int] = None,
            multiLink: bool = False,
            damage: str = '',
            traits: str = ''
            ) -> None:
        self._name = name
        self._techLevel = techLevel
        self._cost = cost
        self._size = size
        self._skill = skill
        self._specialty = specialty
        self._magazineCost = magazineCost
        self._multiLink = multiLink
        self._damage = damage
        self._traits = traits

    def name(self) -> str:
        return self._name
    
    def techLevel(self) -> int:
        return self._techLevel
    
    def cost(self) -> int:
        return self._cost
    
    def size(self) -> int:
        return self._size
    
    def skill(self) -> traveller.SkillDefinition:
        return self._skill
    
    def specialty(self) -> typing.Optional[enum.Enum]:
        return self._specialty

    def magazineCost(self) -> typing.Optional[int]:
        return self._magazineCost
        
    def multiLink(self) -> bool:
        return self._multiLink
    
    def damage(self) -> str:
        return self._damage
    
    def traits(self) -> str:
        return self._traits
    
# List of weapons taken from the MGT2 Robot Worksheet v1.50.01 spreadsheet
# IMPORTANT: These weapon names MUST remain constant between versions otherwise
# it will break weapons saved by older versions
# NOTE: The multilink flag that some weapons have come from the spreadsheet.
# I've not found anything that would indicate it's official but it does seem to
# have some logic behind it. As far as I can tell it's generally weapons that
# are fired rather than wielded or thrown, although there are a few exceptions
# (notably launchers).
# I've kept the value here for completeness but I don't plan to use it. I don't
# see why you couldn't have a multi-linked melee weapon for example. I think
# it's best to allow any weapon to be multi-linked and leave it up to referees
# to say if it's allowed.
TravellerCompanionWeapons = [
    WeaponData(
        name='Aerosol Grenade',
        techLevel=9,
        cost=15,
        size=WeaponSize.Small,
        skill=traveller.AthleticsSkillDefinition,
        specialty=traveller.AthleticsSkillSpecialities.Dexterity,
        traits='Blast 9'),
    WeaponData(
        name='Chemical Grenade',
        techLevel=5,
        cost=50,
        size=WeaponSize.Small,
        skill=traveller.AthleticsSkillDefinition,
        specialty=traveller.AthleticsSkillSpecialities.Dexterity,
        damage='Special',
        traits='Blast 9'),
    WeaponData(
        name='EMP Grenade',
        techLevel=9,
        cost=100,
        size=WeaponSize.Small,
        skill=traveller.AthleticsSkillDefinition,
        specialty=traveller.AthleticsSkillSpecialities.Dexterity,
        traits='Blast 6'),
    WeaponData(
        name='Frag Grenade',
        techLevel=6,
        cost=30,
        size=WeaponSize.Small,
        skill=traveller.AthleticsSkillDefinition,
        specialty=traveller.AthleticsSkillSpecialities.Dexterity,
        damage='5D',
        traits='Blast 9'),
    WeaponData(
        name='Incendiary Grenade',
        techLevel=7,
        cost=75,
        size=WeaponSize.Small,
        skill=traveller.AthleticsSkillDefinition,
        specialty=traveller.AthleticsSkillSpecialities.Dexterity,
        damage='2D',
        traits='Blast 3, Fire'),
    WeaponData(
        name='Neurotoxin Grenade',
        techLevel=9,
        cost=250,
        size=WeaponSize.Small,
        skill=traveller.AthleticsSkillDefinition,
        specialty=traveller.AthleticsSkillSpecialities.Dexterity,
        damage='Special',
        traits='Blast 9'),
    WeaponData(
        name='Plasma Grenade',
        techLevel=16,
        cost=500,
        size=WeaponSize.Small,
        skill=traveller.AthleticsSkillDefinition,
        specialty=traveller.AthleticsSkillSpecialities.Dexterity,
        damage='8D',
        traits='Blast 6'),
    WeaponData(
        name='Smoke Grenade',
        techLevel=6,
        cost=15,
        size=WeaponSize.Small,
        skill=traveller.AthleticsSkillDefinition,
        specialty=traveller.AthleticsSkillSpecialities.Dexterity,
        traits='Blast 9'),
    WeaponData(
        name='Stun Grenade',
        techLevel=7,
        cost=30,
        size=WeaponSize.Small,
        skill=traveller.AthleticsSkillDefinition,
        specialty=traveller.AthleticsSkillSpecialities.Dexterity,
        damage='3D',
        traits='Blast 9, Stun'),
    WeaponData(
        name='Thermal Smoke Grenade',
        techLevel=7,
        cost=30,
        size=WeaponSize.Small,
        skill=traveller.AthleticsSkillDefinition,
        specialty=traveller.AthleticsSkillSpecialities.Dexterity,
        traits='Blast 9'),
    WeaponData(
        name='Tranq Gas Grenade',
        techLevel=8,
        cost=75,
        size=WeaponSize.Small,
        skill=traveller.AthleticsSkillDefinition,
        specialty=traveller.AthleticsSkillSpecialities.Dexterity,
        damage='Special',
        traits='Blast 9'),
    WeaponData(
        name='Breaching Charge',
        techLevel=8,
        cost=250,
        size=WeaponSize.Small,
        skill=traveller.ExplosivesSkillDefinition,
        damage='4D',
        traits='AP 6, Blast 1'),
    WeaponData(
        name='Complex Chemical Charge',
        techLevel=10,
        cost=500,
        size=WeaponSize.Small,
        skill=traveller.ExplosivesSkillDefinition,
        damage='4D',
        traits='AP 15, Blast 9'),
    WeaponData(
        name='Fusion Block',
        techLevel=16,
        cost=10000,
        size=WeaponSize.Small,
        skill=traveller.ExplosivesSkillDefinition,
        damage='1DD',
        traits='AP 50, Blast 12, Radiation'),
    WeaponData(
        name='Neutrino Detonator',
        techLevel=17,
        cost=50000,
        size=WeaponSize.Small,
        skill=traveller.ExplosivesSkillDefinition,
        damage='8D',
        traits='AP ∞, Blast 25'),
    WeaponData(
        name='Plastic Explosive',
        techLevel=6,
        cost=200,
        size=WeaponSize.Small,
        skill=traveller.ExplosivesSkillDefinition,
        damage='3D',
        traits='Blast 9'),
    WeaponData(
        name='Pocket Nuke',
        techLevel=12,
        cost=250000,
        size=WeaponSize.Small,
        skill=traveller.ExplosivesSkillDefinition,
        damage='6DD',
        traits='Blast 1,000, Radiation'),
    WeaponData(
        name='TDX',
        techLevel=12,
        cost=1000,
        size=WeaponSize.Small,
        skill=traveller.ExplosivesSkillDefinition,
        damage='4D',
        traits='Blast 15'),
    WeaponData(
        name='Atlatl',
        techLevel=0,
        cost=20,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Archaic),
    WeaponData(
        name='Compound Cam Bow',
        techLevel=5,
        cost=250,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Archaic,
        magazineCost=5,
        multiLink=True,
        damage='3D-3',
        traits='AP 2, Silent'),
    WeaponData(
        name='Crossbow',
        techLevel=1,
        cost=200,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Archaic,
        magazineCost=1,
        multiLink=True,
        damage='3D-3',
        traits='AP 2, Silent'),
    WeaponData(
        name='Dart',
        techLevel=0, cost=10,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Archaic,
        damage='2D-2',
        traits='One Use, Silent'),
    WeaponData(
        name='Javelin',
        techLevel=0,
        cost=10,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Archaic,
        damage='2D',
        traits='One Use, Silent'),
    WeaponData(
        name='Long Bow',
        techLevel=1,
        cost=150,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Archaic,
        magazineCost=1,
        multiLink=True,
        damage='3D-3',
        traits='AP 2, Silent'),
    WeaponData(
        name='Repeating Crossbow',
        techLevel=2,
        cost=400,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Archaic,
        magazineCost=6,
        multiLink=True,
        damage='2D',
        traits='Silent'),
    WeaponData(
        name='Short Bow',
        techLevel=0,
        cost=50,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Archaic,
        magazineCost=1,
        multiLink=True,
        damage='2D-3',
        traits='Silent'),
    WeaponData(
        name='Cartridge Laser Carbine, TL 10',
        techLevel=10,
        cost=2500,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        magazineCost=70,
        multiLink=True,
        damage='4D',
        traits='Zero-G'),
    WeaponData(
        name='Cartridge Laser Carbine, TL 12',
        techLevel=12,
        cost=4000,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        magazineCost=70,
        multiLink=True,
        damage='4D+3',
        traits='Zero-G'),
    WeaponData(
        name='Cartridge Laser Rifle, TL 10',
        techLevel=10,
        cost=3500,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        magazineCost=150,
        multiLink=True,
        damage='5D',
        traits='Auto 3, Zero-G'),
    WeaponData(
        name='Cartridge Laser Rifle, TL 12',
        techLevel=12,
        cost=8000,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        magazineCost=150,
        multiLink=True,
        damage='5D+3',
        traits='Auto 3, Zero-G'),
    WeaponData(
        name='Cryo Rifle',
        techLevel=13,
        cost=6000,
        size=WeaponSize.Heavy,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        magazineCost=150,
        multiLink=True,
        damage='4D',
        traits='Blast 3'),
    WeaponData(
        name='Flame Rifle',
        techLevel=9,
        cost=2500,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        magazineCost=50,
        multiLink=True,
        damage='4D',
        traits='Blast 3, Fire'),
    WeaponData(
        name='Gauntlet Laser',
        techLevel=10,
        cost=2500,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        magazineCost=1100,
        multiLink=True,
        damage='3D',
        traits='Zero-G'),
    WeaponData(
        name='Hand Flamer',
        techLevel=10,
        cost=1500,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        magazineCost=25,
        multiLink=True,
        damage='3D',
        traits='Blast 2, Fire'),
    WeaponData(
        name='Heavy Laser Rifle',
        techLevel=12,
        cost=14000,
        size=WeaponSize.Heavy,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        magazineCost=500,
        multiLink=True,
        damage='6D',
        traits='Scope, Zero-G'),
    WeaponData(
        name='Ion Rifle, TL 14',
        techLevel=14,
        cost=16000,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        magazineCost=5000,
        multiLink=True,
        damage='Special',
        traits='Zero-G'),
    WeaponData(
        name='Ion Rifle, TL 15',
        techLevel=15,
        cost=24000,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        magazineCost=8000,
        multiLink=True,
        damage='Special',
        traits='Zero-G'),
    WeaponData(
        name='Laser Carbine, TL 11',
        techLevel=11,
        cost=4000,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        magazineCost=3000,
        multiLink=True,
        damage='4D+3',
        traits='Zero-G'),
    WeaponData(
        name='Laser Carbine, TL 9',
        techLevel=9,
        cost=2500,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        magazineCost=1000,
        multiLink=True,
        damage='4D',
        traits='Zero-G'),
    WeaponData(
        name='Laser Pistol, TL 11',
        techLevel=11,
        cost=3000,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        magazineCost=3000,
        multiLink=True,
        damage='3D+3',
        traits='Zero-G'),
    WeaponData(
        name='Laser Pistol, TL 9',
        techLevel=9,
        cost=2000,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        magazineCost=1000,
        multiLink=True,
        damage='3D',
        traits='Zero-G'),
    WeaponData(
        name='Laser Rifle, TL 11',
        techLevel=11,
        cost=8000,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        magazineCost=3500,
        multiLink=True,
        damage='5D+3',
        traits='Zero-G'),
    WeaponData(
        name='Laser Rifle, TL 9',
        techLevel=9,
        cost=3500,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        magazineCost=1500,
        multiLink=True,
        damage='5D',
        traits='Zero-G'),
    WeaponData(
        name='Laser Sniper Rifle',
        techLevel=12,
        cost=9000,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        magazineCost=250,
        multiLink=True,
        damage='5D+3',
        traits='Scope, Zero-G'),
    WeaponData(
        name='Maser Pistol',
        techLevel=17,
        cost=25000,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        multiLink=True,
        damage='3D+3',
        traits='AP 10, Zero-G'),
    WeaponData(
        name='Maser Rifle',
        techLevel=16,
        cost=30000,
        size=WeaponSize.Heavy,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        multiLink=True,
        damage='5D+3',
        traits='AP 10, Zero-G'),
    WeaponData(
        name='Matter Disintegrator, TL 18',
        techLevel=18,
        cost=2500000,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        magazineCost=50000,
        multiLink=True,
        damage='1DD',
        traits='Zero-G'),
    WeaponData(
        name='Matter Disintegrator, TL 19',
        techLevel=19,
        cost=4000000,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        multiLink=True,
        damage='2DD',
        traits='Zero-G'),
    WeaponData(
        name='Pepper Spray',
        techLevel=5,
        cost=5,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        magazineCost=5,
        damage='Special',
        traits='Stun'),
    WeaponData(
        name='Personal Defence Laser',
        techLevel=13,
        cost=6000,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        magazineCost=100,
        multiLink=True,
        damage='3D+3',
        traits='Auto 2, Zero-G'),
    WeaponData(
        name='Plasma Rifle',
        techLevel=16,
        cost=100000,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        multiLink=True,
        damage='6D'),
    WeaponData(
        name='Solar Beam Rifle',
        techLevel=17,
        cost=200000,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        multiLink=True,
        damage='1DD',
        traits='AP 20, Zero-G'),
    WeaponData(
        name='Stagger Laser Rifle, TL 12',
        techLevel=12,
        cost=10000,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        magazineCost=5000,
        multiLink=True,
        damage='5D',
        traits='Auto 2, Zero-G'),
    WeaponData(
        name='Stagger Laser Rifle, TL 14',
        techLevel=14,
        cost=15000,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        magazineCost=6000,
        multiLink=True,
        damage='5D+3',
        traits='Auto 3, Zero-G'),
    WeaponData(
        name='Stun Blaster',
        techLevel=13,
        cost=3000,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        magazineCost=500,
        multiLink=True,
        damage='4D',
        traits='Stun, Zero-G'),
    WeaponData(
        name='Stun Carbine',
        techLevel=12,
        cost=2000,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        magazineCost=200,
        multiLink=True,
        damage='3D',
        traits='Stun, Zero-G'),
    WeaponData(
        name='Stunner, TL 10',
        techLevel=10,
        cost=750,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        magazineCost=200,
        multiLink=True,
        damage='2D+3',
        traits='Stun, Zero-G'),
    WeaponData(
        name='Stunner, TL 12',
        techLevel=12,
        cost=1000,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        magazineCost=200,
        multiLink=True,
        damage='3D',
        traits='Stun, Zero-G'),
    WeaponData(
        name='Stunner, TL 8',
        techLevel=8,
        cost=500,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Energy,
        magazineCost=200,
        multiLink=True,
        damage='2D',
        traits='Stun, Zero-G'),
    WeaponData(
        name='Accelerator Rifle, TL 11',
        techLevel=11,
        cost=1500,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=40,
        multiLink=True,
        damage='3D',
        traits='Zero-G'),
    WeaponData(
        name='Accelerator Rifle, TL 9',
        techLevel=9,
        cost=900,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=30,
        multiLink=True,
        damage='3D',
        traits='Zero-G'),
    WeaponData(
        name='Advanced Combat Rifle',
        techLevel=10,
        cost=1000,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=15,
        multiLink=True,
        damage='3D',
        traits='Auto 3, Scope'),
    WeaponData(
        name='Air Rifle, TL 3',
        techLevel=3,
        cost=225,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=1,
        multiLink=True,
        damage='2D',
        traits='Silent'),
    WeaponData(
        name='Air Rifle, TL 4',
        techLevel=4,
        cost=350,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=1,
        multiLink=True,
        damage='3D-2',
        traits='Silent'),
    WeaponData(
        name='Antique Pistol',
        techLevel=2,
        cost=100,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=5,
        multiLink=True,
        damage='2D-3'),
    WeaponData(
        name='Antique Rifle',
        techLevel=2,
        cost=150,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=10,
        multiLink=True,
        damage='3D-3'),
    WeaponData(
        name='Assault Pistol',
        techLevel=6,
        cost=250,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=10,
        multiLink=True,
        damage='3D-3',
        traits='Auto 2'),
    WeaponData(
        name='Assault Rifle',
        techLevel=7,
        cost=500,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=15,
        multiLink=True,
        damage='3D',
        traits='Auto 2'),
    WeaponData(
        name='Assault Shotgun',
        techLevel=6,
        cost=500,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=40,
        multiLink=True,
        damage='4D',
        traits='Auto 2'),
    WeaponData(
        name='Autopistol',
        techLevel=5,
        cost=200,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=10,
        multiLink=True,
        damage='3D-3'),
    WeaponData(
        name='Autorifle',
        techLevel=6,
        cost=750,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=10,
        multiLink=True,
        damage='3D',
        traits='Auto 2'),
    WeaponData(
        name='Big Game Rifle',
        techLevel=5,
        cost=1250,
        size=WeaponSize.Heavy,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=50,
        multiLink=True,
        damage='3D+3'),
    WeaponData(
        name='Body Pistol',
        techLevel=8,
        cost=500,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=10,
        multiLink=True,
        damage='2D'),
    WeaponData(
        name='Cartridge Pistol',
        techLevel=7,
        cost=300,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=10,
        multiLink=True,
        damage='4D'),
    WeaponData(
        name='Coach Pistol',
        techLevel=3,
        cost=200,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=10,
        multiLink=True,
        damage='4D-3',
        traits='Dangerous'),
    WeaponData(
        name='Duck\'s Foot Pistol',
        techLevel=3,
        cost=300,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=25,
        multiLink=True,
        damage='3D-3',
        traits='Auto 4, Dangerous'),
    WeaponData(
        name='Flechette Pistol',
        techLevel=9,
        cost=275,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=10,
        multiLink=True,
        damage='3D-2',
        traits='Silent'),
    WeaponData(
        name='Flechette Submachine Gun',
        techLevel=9,
        cost=500,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=20,
        multiLink=True,
        damage='3D-2',
        traits='Auto 3, Silent'),
    WeaponData(
        name='Gauss Assault Gun',
        techLevel=12,
        cost=1300,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=35,
        multiLink=True,
        damage='4D',
        traits='AP 5, Auto 2'),
    WeaponData(
        name='Gauss Pistol',
        techLevel=13,
        cost=500,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=20,
        multiLink=True,
        damage='3D',
        traits='AP 3, Auto 2'),
    WeaponData(
        name='Gauss Rifle',
        techLevel=12,
        cost=1500,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=80,
        multiLink=True,
        damage='4D',
        traits='AP 5, Auto 3, Scope'),
    WeaponData(
        name='Gauss Sniper RIfle',
        techLevel=12,
        cost=2500,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=20,
        multiLink=True,
        damage='5D',
        traits='AP 6, Scope'),
    WeaponData(
        name='Gauss Submachine Gun',
        techLevel=12,
        cost=1000,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=60,
        multiLink=True,
        damage='3D+2',
        traits='AP 3, Auto 4'),
    WeaponData(
        name='Heavy Advanced Combat Rifle',
        techLevel=10,
        cost=2000,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=20,
        multiLink=True,
        damage='4D',
        traits='Auto 2, Scope'),
    WeaponData(
        name='Heavy Revolver',
        techLevel=5,
        cost=400,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=15,
        multiLink=True,
        damage='4D-3'),
    WeaponData(
        name='Light Shotgun',
        techLevel=4,
        cost=150,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=10,
        multiLink=True,
        damage='3D'),
    WeaponData(
        name='Magrail Pistol',
        techLevel=14,
        cost=750,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=60,
        multiLink=True,
        damage='3D+3',
        traits='Auto 4'),
    WeaponData(
        name='Magrail Rifle',
        techLevel=14,
        cost=2500,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=100,
        multiLink=True,
        damage='4D+3',
        traits='Auto 6'),
    WeaponData(
        name='Revolver',
        techLevel=4,
        cost=150,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=5,
        multiLink=True,
        damage='3D-3'),
    WeaponData(
        name='Rifle',
        techLevel=5,
        cost=200,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=10,
        multiLink=True,
        damage='3D'),
    WeaponData(
        name='Sawed-Off Shotgun',
        techLevel=4,
        cost=200,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=10,
        multiLink=True,
        damage='4D'),
    WeaponData(
        name='Shot Pistol',
        techLevel=5,
        cost=60,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=5,
        multiLink=True,
        damage='3D'),
    WeaponData(
        name='Shotgun',
        techLevel=4,
        cost=200,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=10,
        multiLink=True,
        damage='4D'),
    WeaponData(
        name='Sniper Rifle',
        techLevel=8,
        cost=700,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=10,
        multiLink=True,
        damage='3D',
        traits='AP 5, Scope, Silent'),
    WeaponData(
        name='Snub Carbine',
        techLevel=11,
        cost=500,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=30,
        multiLink=True,
        damage='3D-3',
        traits='Zero-G'),
    WeaponData(
        name='Snub Pistol',
        techLevel=8,
        cost=150,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=10,
        multiLink=True,
        damage='3D-3',
        traits='Zero-G'),
    WeaponData(
        name='Spear Gun',
        techLevel=6,
        cost=50,
        size=WeaponSize.Medium,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=10,
        multiLink=True,
        damage='3D',
        traits='Silent'),
    WeaponData(
        name='Submachine Gun',
        techLevel=6,
        cost=400,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=10,
        multiLink=True,
        damage='3D',
        traits='Auto 3'),
    WeaponData(
        name='Universal Autopistol',
        techLevel=8,
        cost=300,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=10,
        multiLink=True,
        damage='3D-3'),
    WeaponData(
        name='Zip Gun',
        techLevel=3,
        cost=50,
        size=WeaponSize.Small,
        skill=traveller.GunCombatSkillDefinition,
        specialty=traveller.GunCombatSkillSpecialities.Slug,
        magazineCost=5,
        multiLink=True,
        damage='2D-3',
        traits='Dangerous'),
    WeaponData(
        name='Infantry Mortar',
        techLevel=5,
        cost=3500,
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Artillery,
        magazineCost=50,
        multiLink=True,
        damage='5D',
        traits='Artillery, Blast 5'),
    WeaponData(
        name='Support Mortar',
        techLevel=7,
        cost=11000,
        size=WeaponSize.Vehicle,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Artillery,
        magazineCost=100,
        multiLink=True,
        damage='9D',
        traits='Artillery, Blast 6'),
    WeaponData(
        name='Anti-Material Rifle',
        techLevel=7,
        cost=3000,
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        magazineCost=10,
        multiLink=True,
        damage='5D',
        traits='AP 5, Scope'),
    WeaponData(
        name='ARL (PDW)',
        techLevel=10,
        cost=200,
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        magazineCost=100,
        multiLink=True,
        damage='4D',
        traits='Auto 4, Zero-G'),
    WeaponData(
        name='ARL (Standard)',
        techLevel=10,
        cost=800,
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        magazineCost=100,
        multiLink=True,
        damage='4D',
        traits='Zero-G'),
    WeaponData(
        name='ARL (Support)',
        techLevel=10,
        cost=1300,
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        magazineCost=200,
        multiLink=True,
        damage='4D',
        traits='Auto 4, Zero-G'),
    WeaponData(
        name='CPPG-11',
        techLevel=11,
        cost=8000,
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        magazineCost=300,
        multiLink=True,
        damage='6D',
        traits='AP 6, Blast 2, Scope'),
    WeaponData(
        name='CPPG-12',
        techLevel=12,
        cost=15000,
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        magazineCost=450,
        multiLink=True,
        damage='8D',
        traits='AP 8, Blast 3, Scope'),
    WeaponData(
        name='CPPG-13',
        techLevel=13,
        cost=25000,
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        magazineCost=600,
        multiLink=True,
        damage='1DD',
        traits='AP 10, Blast 3, Scope'),
    WeaponData(
        name='Cryojet',
        techLevel=11,
        cost=4000,
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        magazineCost=200,
        multiLink=True,
        damage='4D',
        traits='Blast 5'),
    WeaponData(
        name='Disposable Plasma Launcher',
        techLevel=12,
        cost=8000,
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        damage='2DD',
        traits='One Use, Smart'),
    WeaponData(
        name='Early Machinegun',
        techLevel=4,
        cost=1200,
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        magazineCost=100,
        multiLink=True,
        damage='3D',
        traits='Auto 3'),
    WeaponData(
        name='FGHP-14',
        techLevel=14,
        cost=100000,
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        multiLink=True,
        damage='2DD',
        traits='Radiation'),
    WeaponData(
        name='FGHP-15',
        techLevel=15,
        cost=400000,
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        multiLink=True,
        damage='2DD',
        traits='Radiation'),
    WeaponData(
        name='FGHP-16',
        techLevel=16,
        cost=500000,
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        multiLink=True,
        damage='2DD',
        traits='Radiation'),
    WeaponData(
        name='Flamethrower, TL 4',
        techLevel=4,
        cost=800,
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        magazineCost=60,
        multiLink=True,
        damage='3D',
        traits='Blast 5, Fire'),
    WeaponData(
        name='Flamethrower, TL 6',
        techLevel=6,
        cost=1500,
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        magazineCost=80,
        multiLink=True,
        damage='4D',
        traits='Blast 5, Fire'),
    WeaponData(
        name='Flamethrower, TL 8',
        techLevel=8,
        cost=2000,
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        magazineCost=100,
        multiLink=True,
        damage='4D',
        traits='Blast 5, Fire'),
    WeaponData(
        name='Grenade Launcher',
        techLevel=7,
        cost=400,
        size=WeaponSize.Medium,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        magazineCost=180,
        damage='As Grenade'),
    WeaponData(
        name='Light Assault Gun',
        techLevel=8,
        cost=4000,
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        magazineCost=100,
        multiLink=True,
        damage='7D',
        traits='AP 5'),
    WeaponData(
        name='Light Gatling Laser',
        techLevel=9,
        cost=4500,
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        magazineCost=300,
        multiLink=True,
        damage='3D',
        traits='Auto 4, Zero-G'),
    WeaponData(
        name='Machinegun',
        techLevel=5,
        cost=1500,
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        magazineCost=100,
        multiLink=True,
        damage='3D',
        traits='Auto 4, Zero-G'),
    WeaponData(
        name='PGHP-12',
        techLevel=12,
        cost=20000,
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        multiLink=True,
        damage='1DD'),
    WeaponData(
        name='PGHP-13',
        techLevel=13,
        cost=65000,
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        multiLink=True,
        damage='1DD'),
    WeaponData(
        name='PGHP-14',
        techLevel=14,
        cost=100000,
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        multiLink=True,
        damage='1DD'),
    WeaponData(
        name='Plasma Jet, TL 12',
        techLevel=12,
        cost=16000,
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        multiLink=True,
        damage='1DD',
        traits='Blast 5'),
    WeaponData(
        name='Plasma Jet, TL 14',
        techLevel=14,
        cost=80000,
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        multiLink=True,
        damage='1DD',
        traits='Blast 10'),
    WeaponData(
        name='RAM Grenade Launcher',
        techLevel=8,
        cost=800,
        size=WeaponSize.Medium,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        magazineCost=240,
        damage='As Grenade',
        traits='Auto 3'),
    WeaponData(
        name='Rapid-Fire Machinegun',
        techLevel=7,
        cost=3000,
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        magazineCost=100,
        multiLink=True,
        damage='3D',
        traits='Auto 4 (8)'),
    WeaponData(
        name='Rocket Launcher, TL 6',
        techLevel=6,
        cost=2000,
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        magazineCost=300,
        damage='4D+3',
        traits='Blast 6'),
    WeaponData(
        name='Rocket Launcher, TL 7',
        techLevel=7,
        cost=2000,
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        magazineCost=400,
        damage='4D',
        traits='Blast 6, Smart'),
    WeaponData(
        name='Rocket Launcher, TL 8',
        techLevel=8,
        cost=2000,
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        magazineCost=600,
        damage='5D',
        traits='Blast 6, Scope, Smart'),
    WeaponData(
        name='Rocket Launcher, TL 9',
        techLevel=9,
        cost=2000,
        size=WeaponSize.Heavy,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Portable,
        magazineCost=800,
        damage='5D+3',
        traits='Blast 6, Scope, Smart'),
    WeaponData(
        name='Heavy Machinegun',
        techLevel=6,
        cost=4500,
        size=WeaponSize.Vehicle,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Vehicle,
        magazineCost=400,
        multiLink=True,
        damage='5D',
        traits='Auto 3'),
    WeaponData(
        name='Light Anti-Air Missile',
        techLevel=7,
        cost=5000,
        size=WeaponSize.Vehicle,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Vehicle,
        damage='6D',
        traits='One Use, Smart'),
    WeaponData(
        name='Light Autocannon',
        techLevel=6,
        cost=10000,
        size=WeaponSize.Vehicle,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Vehicle,
        magazineCost=1000,
        multiLink=True,
        damage='6D',
        traits='Auto 3'),
    WeaponData(
        name='Rocket Pod',
        techLevel=6,
        cost=8000,
        size=WeaponSize.Vehicle,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Vehicle,
        damage='4D',
        traits='Auto 3, Blast 5'),
    WeaponData(
        name='Tac Launcher, Anti-Aircraft',
        techLevel=10,
        cost=16000,
        size=WeaponSize.Vehicle,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Vehicle,
        magazineCost=8000,
        damage='8D',
        traits='Scope, Smart'),
    WeaponData(
        name='Tac Launcher, Anti-Personnel',
        techLevel=10,
        cost=12000,
        size=WeaponSize.Vehicle,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Vehicle,
        magazineCost=4000,
        damage='4D',
        traits='Blast 10, Scope, Smart'),
    WeaponData(
        name='Tac Launcher, Armour Piercing',
        techLevel=10,
        cost=15000,
        size=WeaponSize.Vehicle,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Vehicle,
        magazineCost=6000,
        damage='8D',
        traits='AP 10, Scope, Smart'),
    WeaponData(
        name='VRF Gauss Gun',
        techLevel=12,
        cost=20000,
        size=WeaponSize.Vehicle,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Vehicle,
        magazineCost=1000,
        multiLink=True,
        damage='4D',
        traits='AP 5, Auto 8'),
    WeaponData(
        name='VRF Machinegun',
        techLevel=7,
        cost=12000,
        size=WeaponSize.Vehicle,
        skill=traveller.HeavyWeaponsSkillDefinition,
        specialty=traveller.HeavyWeaponsSkillSpecialities.Vehicle,
        magazineCost=1250,
        multiLink=True,
        damage='4D',
        traits='Auto 6'),
    WeaponData(
        name='Arc-Field Weapon',
        techLevel=14,
        cost=25000,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        damage='5D+2',
        traits='AP 30'),
    WeaponData(
        name='Assault Pike, TL 5',
        techLevel=5,
        cost=200,
        size=WeaponSize.Heavy,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        damage='4D',
        traits='AP 4, One Use'),
    WeaponData(
        name='Assault Pike, TL 8',
        techLevel=8,
        cost=400,
        size=WeaponSize.Medium,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        damage='4D',
        traits='AP 4, One Use'),
    WeaponData(
        name='Battle Axe',
        techLevel=1,
        cost=225,
        size=WeaponSize.Medium,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        damage='3D',
        traits='AP 2'),
    WeaponData(
        name='Blade',
        techLevel=1,
        cost=100,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        damage='2D'),
    WeaponData(
        name='Broadsword',
        techLevel=1,
        cost=500,
        size=WeaponSize.Medium,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        damage='4D'),
    WeaponData(
        name='Chaindrive Axe',
        techLevel=10,
        cost=600,
        size=WeaponSize.Medium,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        damage='4D',
        traits='AP 4'),
    WeaponData(
        name='Chaindrive Sword',
        techLevel=10,
        cost=500,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        damage='4D',
        traits='AP 2'),
    WeaponData(
        name='Cutlass',
        techLevel=2,
        cost=200,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        damage='3D'),
    WeaponData(
        name='Dagger',
        techLevel=1,
        cost=10,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        damage='1D+2'),
    WeaponData(
        name='Great Axe',
        techLevel=1,
        cost=750,
        size=WeaponSize.Heavy,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        damage='4D+2',
        traits='Smasher'),
    WeaponData(
        name='Hatchet',
        techLevel=1,
        cost=50,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        damage='2D+2'),
    WeaponData(
        name='Lance',
        techLevel=1,
        cost=250,
        size=WeaponSize.Medium,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        damage='5D',
        traits='AP 4'),
    WeaponData(
        name='Long Blade, TL 1',
        techLevel=1,
        cost=200,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        damage='3D'),
    WeaponData(
        name='Long Blade, TL 3',
        techLevel=3,
        cost=300,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        damage='3D+2'),
    WeaponData(
        name='Monoblade',
        techLevel=12,
        cost=2500,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        damage='3D',
        traits='AP 10'),
    WeaponData(
        name='Monofilament Axe',
        techLevel=12,
        cost=3000,
        size=WeaponSize.Medium,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        damage='4D'),
    WeaponData(
        name='Piston Spear',
        techLevel=7,
        cost=400,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        damage='3D+2',
        traits='AP 2'),
    WeaponData(
        name='Psi Blade',
        techLevel=16,
        cost=30000,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        damage='2D',
        traits='Special (PSI)'),
    WeaponData(
        name='Psi Dagger',
        techLevel=16,
        cost=25000,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        damage='1D+2',
        traits='Special (PSI)'),
    WeaponData(
        name='Rapier',
        techLevel=2,
        cost=200,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        damage='2D'),
    WeaponData(
        name='Spear',
        techLevel=0,
        cost=10,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        damage='2D'),
    WeaponData(
        name='Static Axe, TL 11',
        techLevel=11,
        cost=750,
        size=WeaponSize.Heavy,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        damage='4D',
        traits='AP 6, Smasher'),
    WeaponData(
        name='Static Axe, TL 12',
        techLevel=12,
        cost=1000,
        size=WeaponSize.Medium,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        damage='4D+2',
        traits='AP 8, Smasher'),
    WeaponData(
        name='Static Blade, TL 11',
        techLevel=11,
        cost=700,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        damage='3D',
        traits='AP 5'),
    WeaponData(
        name='Static Blade, TL 12',
        techLevel=12,
        cost=900,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        damage='3D+2',
        traits='AP 6, Smasher'),
    WeaponData(
        name='Stealth Dagger',
        techLevel=8,
        cost=175,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        damage='1D+2'),
    WeaponData(
        name='Stone Axe',
        techLevel=0,
        cost=5,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        damage='2D+1'),
    WeaponData(
        name='War Pick',
        techLevel=1,
        cost=275,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Blade,
        damage='2D+2',
        traits='AP 4'),
    WeaponData(
        name='Anti-Armour Flail',
        techLevel=8,
        cost=250,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        damage='4D',
        traits='AP 5, One Use'),
    WeaponData(
        name='Boarding Shield',
        techLevel=9,
        cost=1500,
        size=WeaponSize.Medium,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        damage='1D',
        traits='Bulky'),
    WeaponData(
        name='Buckler',
        techLevel=1,
        cost=10,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        damage='1D'),
    WeaponData(
        name='Club',
        techLevel=0,
        cost=0,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        damage='2D'),
    WeaponData(
        name='Expandable Shield',
        techLevel=12,
        cost=2500,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        damage='1D'),
    WeaponData(
        name='Gravitic Shield',
        techLevel=17,
        cost=2500,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        damage='1D'),
    WeaponData(
        name='Gravity Hammer',
        techLevel=13,
        cost=10000,
        size=WeaponSize.Medium,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        damage='5D',
        traits='AP 50, Smasher'),
    WeaponData(
        name='Large Shield',
        techLevel=1,
        cost=200,
        size=WeaponSize.Medium,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        damage='0D'),
    WeaponData(
        name='Mace',
        techLevel=1,
        cost=20,
        size=WeaponSize.Medium,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        damage='2D+2',
        traits='Smasher'),
    WeaponData(
        name='Riot Shield',
        techLevel=6,
        cost=175,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        damage='1D'),
    WeaponData(
        name='Sap',
        techLevel=1,
        cost=30,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        damage='1D',
        traits='Stun'),
    WeaponData(
        name='Shield',
        techLevel=0,
        cost=150,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        damage='1D'),
    WeaponData(
        name='Sledgehammer',
        techLevel=1,
        cost=30,
        size=WeaponSize.Heavy,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        damage='4D',
        traits='Smasher'),
    WeaponData(
        name='Staff',
        techLevel=1,
        cost=5,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        damage='2D'),
    WeaponData(
        name='Static Maul',
        techLevel=11,
        cost=650,
        size=WeaponSize.Medium,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        damage='3D',
        traits='AP 4, Smasher'),
    WeaponData(
        name='Stunstick',
        techLevel=8,
        cost=300,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Bludgeon,
        damage='2D',
        traits='Stun'),
    WeaponData(
        name='Brass Knuckles',
        techLevel=1,
        cost=10,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Unarmed,
        damage='1D+2'),
    WeaponData(
        name='Claw, Arc-Field',
        techLevel=14,
        cost=25000,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Unarmed,
        damage='4D',
        traits='AP 30'),
    WeaponData(
        name='Claw, Edging',
        techLevel=11,
        cost=3000,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Unarmed,
        damage='2D+2',
        traits='AP 4'),
    WeaponData(
        name='Claw, Hardened',
        techLevel=10,
        cost=1000,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Unarmed,
        damage='1D+2',
        traits='AP 2'),
    WeaponData(
        name='Claw, Monofilament',
        techLevel=12,
        cost=5000,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Unarmed,
        damage='3D',
        traits='AP 10'),
    WeaponData(
        name='Garotte',
        techLevel=0,
        cost=10,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Unarmed,
        damage='2D'),
    WeaponData(
        name='Handspikes',
        techLevel=2,
        cost=100,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Unarmed,
        damage='2D'),
    WeaponData(
        name='Knuckleblasters',
        techLevel=8,
        cost=150,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Unarmed,
        damage='5D'),
    WeaponData(
        name='Monofilament Garotte',
        techLevel=12,
        cost=1000,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Unarmed,
        damage='3D',
        traits='AP 10, Dangerous'),
    WeaponData(
        name='Piston Fist',
        techLevel=9,
        cost=150,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Unarmed,
        damage='3D+2'),
    WeaponData(
        name='Stunfist',
        techLevel=8,
        cost=250,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Unarmed,
        damage='1D+2',
        traits='Stun'),
    WeaponData(
        name='Shock Whip',
        techLevel=9,
        cost=450,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Whip,
        damage='2D',
        traits='Stun'),
    WeaponData(
        name='Whip',
        techLevel=1,
        cost=15,
        size=WeaponSize.Small,
        skill=traveller.MeleeSkillDefinition,
        specialty=traveller.MeleeSkillSpecialities.Whip,
        damage='D3')
]

TravellerCompanionWeaponDataMap = {weapon.name(): weapon for weapon in TravellerCompanionWeapons}